"""Executive dashboard: gap analysis and progress tracking (Sprint 6).

Sprint 6 of the two-part Executive Reporting epic (see the
executive-reporting skill's "Example usage" note: Sprint 6 is
dashboard/analytics, Sprint 7 is PDF/XLSX generation — not built here).

Structures a single assessment's current state using the
situation/complication/resolution convention: what was assessed
(situation), where it falls short grouped MECE by domain
(complication), and a prioritized, effort-based gap list (resolution).
Every number carries a templated "so what" sentence, per the skill's
rule against presenting a figure without a business-consequence
sentence attached — templated from real computed values, never
generated by a model, consistent with this project's standing "verified
over fabricated" discipline (this sprint still has no LLM in the loop
at all; see ADR-0011).
"""

from __future__ import annotations

from typing import NamedTuple

from compliance_platform.models.assessment import (
    Assessment,
    EvidenceLink,
    EvidenceReviewStatus,
    PracticeFinding,
    PracticeFindingStatus,
)
from compliance_platform.models.framework import Domain, FrameworkDefinition
from compliance_platform.models.report import (
    DashboardReport,
    DomainGapGroup,
    EvidenceCitation,
    GapItem,
    OverallSummary,
    ResolutionItem,
    Situation,
)
from compliance_platform.services.scoring_service import compute_assessment_domain_scores

# Findings that override an unmet practice back to "not a gap" if it has
# accepted/edited evidence. PARTIALLY_SATISFIED and NOT_SATISFIED never
# count as performed even with accepted evidence — a reviewer's explicit
# "this isn't (fully) met" judgment overrides a possibly-stale acceptance.
_NEVER_PERFORMED_STATUSES = (
    PracticeFindingStatus.NOT_SATISFIED,
    PracticeFindingStatus.INSUFFICIENT_EVIDENCE,
    PracticeFindingStatus.PARTIALLY_SATISFIED,
)


class PracticeScoringCredit(NamedTuple):
    """The outcome of folding PracticeFinding judgments onto evidence.

    `unsupported_*` are findings that changed nothing because they lack
    the evidence this project requires before a judgment may move a
    score. They are returned rather than discarded so callers can
    surface them: a finding that a reviewer believes is counting, and
    silently is not, is worse than one that visibly blocks.
    """

    performed_practice_ids: set[str]
    excluded_practice_ids: frozenset[str]
    unsupported_satisfied: frozenset[str]
    unsupported_not_applicable: frozenset[str]


def performed_and_excluded_practice_ids(
    evidence_links: list[EvidenceLink], findings: list[PracticeFinding]
) -> PracticeScoringCredit:
    """Folds explicit PracticeFinding overrides (ADR-0030) on top of the
    evidence-link-derived "performed" set.

    **Positive scoring credit requires evidence** (ADR-0057, superseding
    only ADR-0030 Decision 3's "SATISFIED counts a practice as performed
    even with no accepted evidence link"). That clause conflicted
    directly with this repository's governing invariant — AGENTS.md rule
    2 and `.cursor/rules/assessment-generation.mdc`: "No score exists
    without a linked evidence trail. Every practice-level maturity score
    must reference the specific evidence item(s) and mapping decision(s)
    that produced it." A SATISFIED finding with no accepted or edited
    link cannot answer "why is this MIL2 and not MIL1" with anything but
    a free-text rationale, which is an assertion, not evidence.

    Concretely:

    - Only ACCEPTED/EDITED links confer credit. PENDING never does —
      that is the human-in-the-loop review step, and counting an
      unreviewed AI proposal would auto-accept it by the back door.
      REJECTED never does either.
    - SATISFIED keeps a practice performed *when it is evidence-backed*.
      Without such a link it is retained as a recorded human judgment
      (the PracticeFinding row and its append-only history are
      untouched) but confers no score, and is reported in
      `unsupported_satisfied`.
    - NOT_APPLICABLE changes the scoring *denominator*, which moves the
      score just as surely as the numerator does, so it carries the same
      evidence requirement. Without a supporting link the practice stays
      in the denominator and is reported in `unsupported_not_applicable`.
    - NOT_SATISFIED / INSUFFICIENT_EVIDENCE / PARTIALLY_SATISFIED still
      remove a practice from "performed" even when evidence was once
      accepted. These are *negative* judgments: they lower or hold a
      score, so requiring evidence to record one would be backwards —
      the risk this invariant guards against is unsupported credit, not
      unsupported caution.

    Shared by services/assessment_service.py.compute_scores and
    build_dashboard below, so scores, the score endpoint and the
    dashboard's gap list can never disagree about which practices are
    performed for a given assessment.
    """
    evidence_backed = {
        link.practice_reference
        for link in evidence_links
        if link.review_status in (EvidenceReviewStatus.ACCEPTED, EvidenceReviewStatus.EDITED)
    }
    performed_practice_ids = set(evidence_backed)
    excluded_practice_ids: set[str] = set()
    unsupported_satisfied: set[str] = set()
    unsupported_not_applicable: set[str] = set()

    for finding in findings:
        reference = finding.practice_reference
        if finding.status == PracticeFindingStatus.SATISFIED:
            if reference in evidence_backed:
                performed_practice_ids.add(reference)
            else:
                unsupported_satisfied.add(reference)
        elif finding.status in _NEVER_PERFORMED_STATUSES:
            performed_practice_ids.discard(reference)
        if finding.status == PracticeFindingStatus.NOT_APPLICABLE:
            if reference in evidence_backed:
                excluded_practice_ids.add(reference)
            else:
                unsupported_not_applicable.add(reference)

    return PracticeScoringCredit(
        performed_practice_ids,
        frozenset(excluded_practice_ids),
        frozenset(unsupported_satisfied),
        frozenset(unsupported_not_applicable),
    )


def _build_situation(
    assessment: Assessment,
    framework: FrameworkDefinition,
    evidence_links: list[EvidenceLink],
    credit: PracticeScoringCredit,
) -> Situation:
    counts = {status: 0 for status in EvidenceReviewStatus}
    for link in evidence_links:
        counts[link.review_status] += 1
    unpopulated = [d.short_code for d in framework.domains if not d.practices_populated]
    # Sorted so the dashboard, the export and the readiness endpoint list
    # the same practices in the same order rather than in set-iteration
    # order, which varies between processes.
    unsupported_satisfied = sorted(credit.unsupported_satisfied)
    unsupported_not_applicable = sorted(credit.unsupported_not_applicable)
    return Situation(
        assessment_id=assessment.id,
        assessment_name=assessment.name,
        framework_name=framework.name,
        scoring_model=framework.scoring_model,
        status=assessment.status.value,
        total_evidence_links=len(evidence_links),
        accepted_count=counts[EvidenceReviewStatus.ACCEPTED],
        edited_count=counts[EvidenceReviewStatus.EDITED],
        rejected_count=counts[EvidenceReviewStatus.REJECTED],
        pending_ai_review_count=counts[EvidenceReviewStatus.PENDING],
        unpopulated_domains=unpopulated,
        unsupported_satisfied_practices=unsupported_satisfied,
        unsupported_not_applicable_practices=unsupported_not_applicable,
        so_what=_situation_so_what(
            total=len(evidence_links),
            accepted=counts[EvidenceReviewStatus.ACCEPTED],
            edited=counts[EvidenceReviewStatus.EDITED],
            rejected=counts[EvidenceReviewStatus.REJECTED],
            pending=counts[EvidenceReviewStatus.PENDING],
            unpopulated=unpopulated,
            status=assessment.status.value,
            unsupported_satisfied=unsupported_satisfied,
            unsupported_not_applicable=unsupported_not_applicable,
        ),
    )


def _situation_so_what(
    total: int,
    accepted: int,
    edited: int,
    rejected: int,
    pending: int,
    unpopulated: list[str],
    status: str,
    unsupported_satisfied: list[str] | None = None,
    unsupported_not_applicable: list[str] | None = None,
) -> list[str]:
    """One consequence sentence per number that has one.

    Deliberately not a sentence per field. Padding every count with
    filler ("4 items were rejected, which means 4 items were rejected")
    would satisfy the letter of executive-reporting.mdc and defeat its
    purpose, which is that a reader should not have to work out why a
    number matters. A count only earns a line here when its value
    changes what someone should do or how far they should trust the
    report.
    """
    lines: list[str] = []
    unsupported_satisfied = unsupported_satisfied or []
    unsupported_not_applicable = unsupported_not_applicable or []

    # Stated before anything else, including the empty-assessment case: a
    # judgment that a reviewer believes is counting and silently is not
    # misleads more than a missing number does (ADR-0057).
    if unsupported_satisfied:
        lines.append(
            f"{len(unsupported_satisfied)} practice(s) marked SATISFIED "
            f"({', '.join(unsupported_satisfied[:5])}"
            f"{', …' if len(unsupported_satisfied) > 5 else ''}) have no accepted or edited "
            "evidence link, so they are recorded as judgments but contribute no score — link "
            "supporting evidence, or the finding will not appear in any figure below."
        )
    if unsupported_not_applicable:
        lines.append(
            f"{len(unsupported_not_applicable)} practice(s) marked NOT_APPLICABLE "
            f"({', '.join(unsupported_not_applicable[:5])}"
            f"{', …' if len(unsupported_not_applicable) > 5 else ''}) have no accepted or edited "
            "evidence link, so they remain in the scoring denominator — an exclusion moves the "
            "score and therefore needs the same evidence basis as a positive finding."
        )

    if total == 0:
        lines.append(
            "No evidence has been linked yet, so every practice in this framework is currently "
            "unassessed — the scores below reflect an empty assessment, not a compliant one."
        )
        return lines

    # The trust question, and the reason this is first: an executive
    # reading a maturity score needs to know how much of it rests on
    # findings a human has actually confirmed.
    reviewed = accepted + edited
    if pending:
        lines.append(
            f"{pending} of {total} evidence links are still AI-proposed and unreviewed, so this "
            "report is provisional: those findings have not been confirmed by a person and should "
            "not be presented as assessed until they are."
        )
    else:
        lines.append(
            f"All {total} evidence links have been human-reviewed, so the findings below rest on "
            "confirmed evidence rather than unreviewed AI proposals."
        )

    if rejected:
        lines.append(
            f"{rejected} proposed link(s) were reviewed and rejected — evidence was considered "
            "and judged not to support the practice, which is a deliberate finding, not a gap in "
            "review."
        )

    if edited:
        lines.append(
            f"{edited} link(s) were accepted only after a reviewer edited them, indicating the "
            "retrieval was close but not correct on its own for those practices."
        )

    if unpopulated:
        lines.append(
            f"{len(unpopulated)} domain(s) ({', '.join(unpopulated)}) have no transcribed "
            "practices yet, so they are excluded from scoring entirely — overall figures describe "
            "the remaining domains only and understate the work outstanding."
        )

    if status != "finalized":
        lines.append(
            f"This assessment is still {status.replace('_', ' ')}, so the figures can change; they "
            "are a working position rather than a signed-off result."
        )

    # Only claim confirmed coverage when there is some AND nothing is
    # pending -- otherwise the reassuring sentence would sit directly
    # under the warning that contradicts it.
    if reviewed and not pending:
        lines.append(
            f"{reviewed} human-confirmed link(s) are available to cite as evidence in the gap "
            "analysis below."
        )

    return lines


def _domain_so_what(
    scoring_model: str, domain_full_name: str, met: int, total: int, score: float
) -> str:
    if total == 0:
        return f"{domain_full_name} has no transcribed practices yet and cannot be assessed."
    if met == total:
        return (
            f"{domain_full_name} is fully covered by reviewed evidence "
            f"({met} of {total} practices)."
        )
    if scoring_model == "cumulative_mil":
        if score == 0:
            return (
                f"{domain_full_name} has not yet reached MIL1: {total - met} of {total} "
                "practices still need evidence, blocking any maturity credit for this domain."
            )
        return (
            f"{domain_full_name} is at MIL{int(score)}: {total - met} of {total} practices "
            "still need evidence before the next MIL level is reachable."
        )
    covered_pct = met / total
    return (
        f"{domain_full_name} is at {covered_pct:.0%} coverage: {total - met} of {total} "
        "subcategories still lack accepted evidence."
    )


def _build_complication(
    framework: FrameworkDefinition,
    performed_practice_ids: set[str],
    excluded_practice_ids: frozenset[str],
    pending_practice_ids: set[str],
    domain_scores: dict[str, float],
    findings_by_practice: dict[str, PracticeFinding],
    evidence_links_by_practice: dict[str, list[EvidenceLink]],
    superseded_document_ids: frozenset[str],
) -> list[DomainGapGroup]:
    groups: list[DomainGapGroup] = []
    for domain in framework.domains:
        if not domain.practices_populated:
            continue
        # NOT_APPLICABLE practices (ADR-0030) are excluded entirely —
        # neither a gap nor counted toward this domain's total, the same
        # denominator scoring_service.py's compute_domain_coverage uses.
        applicable_practices = [
            p for p in domain.all_practices() if p.id not in excluded_practice_ids
        ]
        total = len(applicable_practices)
        gaps = []
        for p in applicable_practices:
            if p.id in performed_practice_ids:
                continue
            finding = findings_by_practice.get(p.id)
            gaps.append(
                GapItem(
                    practice_id=p.id,
                    practice_text=p.text,
                    mil=p.mil,
                    has_pending_ai_proposal=p.id in pending_practice_ids,
                    status=(
                        finding.status if finding else PracticeFindingStatus.INSUFFICIENT_EVIDENCE
                    ),
                    finding_rationale=finding.rationale if finding else None,
                    cited_evidence=[
                        EvidenceCitation(
                            evidence_link_id=link.id,
                            document_id=link.document_id,
                            review_status=link.review_status,
                            is_superseded=link.document_id in superseded_document_ids,
                        )
                        for link in evidence_links_by_practice.get(p.id, [])
                    ],
                )
            )
        if not gaps:
            continue
        gaps.sort(key=lambda g: (g.mil is None, g.mil if g.mil is not None else 0))
        met = total - len(gaps)
        groups.append(
            DomainGapGroup(
                domain_short_code=domain.short_code,
                domain_full_name=domain.full_name,
                total_practices=total,
                met_practices=met,
                gaps=gaps,
                so_what=_domain_so_what(
                    framework.scoring_model,
                    domain.full_name,
                    met,
                    total,
                    domain_scores[domain.short_code],
                ),
            )
        )
    return groups


def _build_resolution(complication: list[DomainGapGroup]) -> list[ResolutionItem]:
    """Sorted by fewest missing practices first — the concrete "quick
    win" framing: a small, closeable gap is the highest-leverage next
    action a reviewer can take, without inventing a fabricated
    business-impact score this project has no basis to assign (see
    ADR-0012).
    """
    ranked = sorted(complication, key=lambda g: len(g.gaps))
    resolution: list[ResolutionItem] = []
    for group in ranked:
        if group.met_practices == 0:
            rationale = (
                f"No evidence yet for this domain; closing {len(group.gaps)} practice(s) "
                "would establish its first maturity credit."
            )
        else:
            rationale = (
                f"Already {group.met_practices} of {group.total_practices} practices met; "
                f"only {len(group.gaps)} remaining to fully close this domain."
            )
        resolution.append(
            ResolutionItem(
                domain_short_code=group.domain_short_code,
                domain_full_name=group.domain_full_name,
                missing_count=len(group.gaps),
                rationale=rationale,
            )
        )
    return resolution


def _build_overall_summary(
    framework: FrameworkDefinition,
    domain_scores: dict[str, float],
    excluded_practice_ids: frozenset[str],
) -> OverallSummary:
    populated_domains = [d for d in framework.domains if d.practices_populated]
    populated_count = len(populated_domains)
    total_count = len(framework.domains)

    if framework.scoring_model == "cumulative_mil":
        at_mil1_plus = sum(1 for d in populated_domains if domain_scores[d.short_code] >= 1.0)
        unpopulated_note = (
            f" ({total_count - populated_count} domain(s) not yet transcribed into the "
            "platform's schema, excluded from this count)"
            if populated_count < total_count
            else ""
        )
        headline = (
            f"{at_mil1_plus} of {populated_count} assessable domains have reached MIL1 or "
            f"higher{unpopulated_note}."
        )
        return OverallSummary(
            scoring_model=framework.scoring_model,
            headline=headline,
            populated_domains=populated_count,
            total_domains=total_count,
            domains_at_mil1_or_above=at_mil1_plus,
        )

    # ADR-0030: weight each domain by its applicable (non-NOT_APPLICABLE)
    # practice count, the same denominator compute_domain_coverage used
    # to produce domain_scores — otherwise this weighted average would
    # silently disagree with the per-domain numbers it's built from.
    def _applicable_count(d: Domain) -> int:
        return len(d.practice_ids() - excluded_practice_ids)

    total_practices = sum(_applicable_count(d) for d in populated_domains)
    if total_practices == 0:
        fraction = 0.0
    else:
        covered = sum(
            round(domain_scores[d.short_code] * _applicable_count(d)) for d in populated_domains
        )
        fraction = covered / total_practices
    unpopulated_note = (
        f" ({total_count - populated_count} domain(s) not yet transcribed, excluded)"
        if populated_count < total_count
        else ""
    )
    headline = (
        f"{fraction:.0%} of assessable subcategories have accepted evidence{unpopulated_note}."
    )
    return OverallSummary(
        scoring_model=framework.scoring_model,
        headline=headline,
        populated_domains=populated_count,
        total_domains=total_count,
        overall_coverage_fraction=fraction,
    )


def build_dashboard(
    assessment: Assessment,
    framework: FrameworkDefinition,
    evidence_links: list[EvidenceLink],
    findings: list[PracticeFinding] | None = None,
    superseded_document_ids: frozenset[str] | set[str] | None = None,
) -> DashboardReport:
    findings = findings if findings is not None else []
    superseded_document_ids = frozenset(superseded_document_ids or ())
    credit = performed_and_excluded_practice_ids(evidence_links, findings)
    performed_practice_ids = credit.performed_practice_ids
    excluded_practice_ids = credit.excluded_practice_ids
    pending_practice_ids = {
        link.practice_reference
        for link in evidence_links
        if link.review_status == EvidenceReviewStatus.PENDING
    }
    domain_scores = compute_assessment_domain_scores(
        framework, performed_practice_ids, excluded_practice_ids
    )
    findings_by_practice = {f.practice_reference: f for f in findings}
    evidence_links_by_practice: dict[str, list[EvidenceLink]] = {}
    for link in evidence_links:
        evidence_links_by_practice.setdefault(link.practice_reference, []).append(link)
    complication = _build_complication(
        framework,
        performed_practice_ids,
        excluded_practice_ids,
        pending_practice_ids,
        domain_scores,
        findings_by_practice,
        evidence_links_by_practice,
        superseded_document_ids,
    )
    return DashboardReport(
        situation=_build_situation(assessment, framework, evidence_links, credit),
        domain_scores=domain_scores,
        overall=_build_overall_summary(framework, domain_scores, excluded_practice_ids),
        complication=complication,
        resolution=_build_resolution(complication),
    )
