"""Is the export in someone's hands still current? (ADR-0077)

R-21, open since Sprint 7: a downloaded PDF/XLSX is a point-in-time
snapshot, and nothing stops a board or a reviewer acting on a stale one
after evidence has since been reviewed, added or rejected. ADR-0013
deliberately does not persist exports, so the platform has no record of
which snapshot is in circulation and cannot chase one.

What it can do is let the holder ask. Every export prints a digest of
the numbers it was generated from; this module computes that digest and
compares one back.

Deliberately NOT the audit seal (ADR-0060), which answers a different
question. The seal asks "has this finalized record been altered?" and is
about tamper-evidence on an immutable record. This asks "have the
numbers moved since this paper was printed?" and is about a living draft
that is *supposed* to change. Same technique, opposite subject: a
superseded report is normal and expected, an altered seal is a finding.
"""

from __future__ import annotations

import hashlib
import json

from compliance_platform.models.report import (
    DashboardReport,
    ReportCurrency,
    ReportCurrencyStatus,
)

# Bumped only when the canonical payload below changes shape. Printed
# alongside the digest so a report generated by an older build can be
# recognised rather than silently reported as superseded -- the same
# reason ADR-0060 versions its seal payload, learned there rather than
# re-learned here.
CURRENT_PAYLOAD_VERSION = "1"


def _payload_v1(dashboard: DashboardReport) -> dict:
    """The numbers a reader acts on, and nothing else.

    Deliberately a chosen subset rather than the whole DashboardReport.
    That model gains fields regularly -- three times in the last four
    sprints -- and digesting all of it would make every previously
    issued export report itself superseded the moment an unrelated field
    was added, which is worse than useless: it would train people to
    ignore the answer.

    So this covers what would change a decision: the scores, the
    headline figures, how much evidence is reviewed and how, and which
    practices are unmet. A cosmetic addition elsewhere leaves an
    existing report correctly reported as current.
    """
    situation = dashboard.situation
    overall = dashboard.overall
    return {
        "payload_version": CURRENT_PAYLOAD_VERSION,
        "assessment_id": situation.assessment_id,
        "status": situation.status,
        "scoring_model": overall.scoring_model,
        "headline": overall.headline,
        "populated_domains": overall.populated_domains,
        "total_domains": overall.total_domains,
        "domains_at_mil1_or_above": overall.domains_at_mil1_or_above,
        "overall_coverage_fraction": overall.overall_coverage_fraction,
        "domain_scores": dict(sorted(dashboard.domain_scores.items())),
        "review": {
            "total": situation.total_evidence_links,
            "accepted": situation.accepted_count,
            "edited": situation.edited_count,
            "rejected": situation.rejected_count,
            "pending": situation.pending_ai_review_count,
        },
        # Which practices are unmet, not how many: a gap closing and
        # another opening is a real change to what the report says, and
        # a count alone would call that no change at all.
        "unmet_practices": sorted(
            gap.practice_id for group in dashboard.complication for gap in group.gaps
        ),
    }


def report_digest(dashboard: DashboardReport) -> str:
    """SHA-256 over the canonical payload. Sorted keys and no whitespace,
    so the same record digests identically on any machine and in any
    process."""
    canonical = json.dumps(_payload_v1(dashboard), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _current_figures(payload: dict) -> list[str]:
    """What the record says NOW, for the holder to compare by eye.

    A digest is one-way: this cannot reconstruct what the reader's copy
    said, so it cannot honestly produce a diff. Stating the current
    figures and letting them compare against the printed page is the
    real thing that can be offered -- and pretending to a change list
    would be inventing one, which is the failure mode this whole project
    is organised against.
    """
    review = payload["review"]
    figures = [
        f"Current status: {payload['status']}.",
        f"Current headline: {payload['headline']}",
        (
            f"Evidence now: {review['total']} link(s) — {review['accepted']} accepted, "
            f"{review['edited']} edited, {review['rejected']} rejected, "
            f"{review['pending']} awaiting review."
        ),
        f"Unmet practices now: {len(payload['unmet_practices'])}.",
    ]
    scores = payload["domain_scores"]
    if scores:
        rendered = ", ".join(f"{domain} {score:g}" for domain, score in scores.items())
        figures.append(f"Current domain scores: {rendered}.")
    figures.append(
        "Compare these against the figures printed on your copy. This check can tell you the "
        "report is out of date; it cannot tell you what it used to say, because the digest is "
        "one-way by design."
    )
    return figures


def check_currency(dashboard: DashboardReport, claimed_digest: str | None) -> ReportCurrency:
    """Compare a digest printed on an export against the record now.

    An unknown or absent digest is UNVERIFIABLE, never SUPERSEDED. A
    report this build cannot check is not evidence that anything
    changed, and saying otherwise would raise a false alarm about a
    document that may be perfectly current -- the same distinction
    ADR-0060 draws between `altered` and `unverifiable`.
    """
    current_payload = _payload_v1(dashboard)
    current = report_digest(dashboard)

    if not claimed_digest:
        return ReportCurrency(
            status=ReportCurrencyStatus.UNVERIFIABLE,
            current_digest=current,
            payload_version=CURRENT_PAYLOAD_VERSION,
            changes=[
                "No report digest was supplied. Exports generated before ADR-0077 do not carry "
                "one and cannot be checked; the generation timestamp printed on them is the only "
                "clue to their age."
            ],
        )

    claimed = claimed_digest.strip().lower()
    if claimed == current:
        return ReportCurrency(
            status=ReportCurrencyStatus.CURRENT,
            claimed_digest=claimed,
            current_digest=current,
            payload_version=CURRENT_PAYLOAD_VERSION,
        )

    return ReportCurrency(
        status=ReportCurrencyStatus.SUPERSEDED,
        claimed_digest=claimed,
        current_digest=current,
        payload_version=CURRENT_PAYLOAD_VERSION,
        # What the record says now, not a diff. See _current_figures.
        changes=_current_figures(current_payload),
    )
