"""Executive dashboard: gap analysis and progress tracking (Sprint 6).

Sprint 6 of the two-part Executive Reporting epic (see the
executive-reporting skill's "Example usage" note: Sprint 6 is
dashboard/analytics, Sprint 7 is PDF/XLSX generation — not built here).

Structures a single assessment's current state using the
situation/complication/resolution convention: what was assessed
(situation), where it falls short grouped MECE by domain
(complication), and a prioritized, effort-based gap list (resolution).
Every number carries a templated "so what" sentence, per the skill's
rule against presenting a figure without a business-consequence
sentence attached — templated from real computed values, never
generated by a model, consistent with this project's standing "verified
over fabricated" discipline (this sprint still has no LLM in the loop
at all; see ADR-0011).
"""

from __future__ import annotations

from compliance_platform.models.assessment import Assessment, EvidenceLink, EvidenceReviewStatus
from compliance_platform.models.framework import FrameworkDefinition
from compliance_platform.models.report import (
    DashboardReport,
    DomainGapGroup,
    GapItem,
    OverallSummary,
    ResolutionItem,
    Situation,
)
from compliance_platform.services.scoring_service import compute_assessment_domain_scores


def _build_situation(
    assessment: Assessment,
    framework: FrameworkDefinition,
    evidence_links: list[EvidenceLink],
) -> Situation:
    counts = {status: 0 for status in EvidenceReviewStatus}
    for link in evidence_links:
        counts[link.review_status] += 1
    unpopulated = [d.short_code for d in framework.domains if not d.practices_populated]
    return Situation(
        assessment_id=assessment.id,
        assessment_name=assessment.name,
        framework_name=framework.name,
        scoring_model=framework.scoring_model,
        status=assessment.status.value,
        total_evidence_links=len(evidence_links),
        accepted_count=counts[EvidenceReviewStatus.ACCEPTED],
        edited_count=counts[EvidenceReviewStatus.EDITED],
        rejected_count=counts[EvidenceReviewStatus.REJECTED],
        pending_ai_review_count=counts[EvidenceReviewStatus.PENDING],
        unpopulated_domains=unpopulated,
    )


def _domain_so_what(
    scoring_model: str, domain_full_name: str, met: int, total: int, score: float
) -> str:
    if total == 0:
        return f"{domain_full_name} has no transcribed practices yet and cannot be assessed."
    if met == total:
        return (
            f"{domain_full_name} is fully covered by reviewed evidence "
            f"({met} of {total} practices)."
        )
    if scoring_model == "cumulative_mil":
        if score == 0:
            return (
                f"{domain_full_name} has not yet reached MIL1: {total - met} of {total} "
                "practices still need evidence, blocking any maturity credit for this domain."
            )
        return (
            f"{domain_full_name} is at MIL{int(score)}: {total - met} of {total} practices "
            "still need evidence before the next MIL level is reachable."
        )
    covered_pct = met / total
    return (
        f"{domain_full_name} is at {covered_pct:.0%} coverage: {total - met} of {total} "
        "subcategories still lack accepted evidence."
    )


def _build_complication(
    framework: FrameworkDefinition,
    performed_practice_ids: set[str],
    pending_practice_ids: set[str],
    domain_scores: dict[str, float],
) -> list[DomainGapGroup]:
    groups: list[DomainGapGroup] = []
    for domain in framework.domains:
        if not domain.practices_populated:
            continue
        all_practices = domain.all_practices()
        total = len(all_practices)
        gaps = [
            GapItem(
                practice_id=p.id,
                practice_text=p.text,
                mil=p.mil,
                has_pending_ai_proposal=p.id in pending_practice_ids,
            )
            for p in all_practices
            if p.id not in performed_practice_ids
        ]
        if not gaps:
            continue
        gaps.sort(key=lambda g: (g.mil is None, g.mil if g.mil is not None else 0))
        met = total - len(gaps)
        groups.append(
            DomainGapGroup(
                domain_short_code=domain.short_code,
                domain_full_name=domain.full_name,
                total_practices=total,
                met_practices=met,
                gaps=gaps,
                so_what=_domain_so_what(
                    framework.scoring_model,
                    domain.full_name,
                    met,
                    total,
                    domain_scores[domain.short_code],
                ),
            )
        )
    return groups


def _build_resolution(complication: list[DomainGapGroup]) -> list[ResolutionItem]:
    """Sorted by fewest missing practices first — the concrete "quick
    win" framing: a small, closeable gap is the highest-leverage next
    action a reviewer can take, without inventing a fabricated
    business-impact score this project has no basis to assign (see
    ADR-0012).
    """
    ranked = sorted(complication, key=lambda g: len(g.gaps))
    resolution: list[ResolutionItem] = []
    for group in ranked:
        if group.met_practices == 0:
            rationale = (
                f"No evidence yet for this domain; closing {len(group.gaps)} practice(s) "
                "would establish its first maturity credit."
            )
        else:
            rationale = (
                f"Already {group.met_practices} of {group.total_practices} practices met; "
                f"only {len(group.gaps)} remaining to fully close this domain."
            )
        resolution.append(
            ResolutionItem(
                domain_short_code=group.domain_short_code,
                domain_full_name=group.domain_full_name,
                missing_count=len(group.gaps),
                rationale=rationale,
            )
        )
    return resolution


def _build_overall_summary(
    framework: FrameworkDefinition, domain_scores: dict[str, float]
) -> OverallSummary:
    populated_domains = [d for d in framework.domains if d.practices_populated]
    populated_count = len(populated_domains)
    total_count = len(framework.domains)

    if framework.scoring_model == "cumulative_mil":
        at_mil1_plus = sum(1 for d in populated_domains if domain_scores[d.short_code] >= 1.0)
        unpopulated_note = (
            f" ({total_count - populated_count} domain(s) not yet transcribed into the "
            "platform's schema, excluded from this count)"
            if populated_count < total_count
            else ""
        )
        headline = (
            f"{at_mil1_plus} of {populated_count} assessable domains have reached MIL1 or "
            f"higher{unpopulated_note}."
        )
        return OverallSummary(
            scoring_model=framework.scoring_model,
            headline=headline,
            populated_domains=populated_count,
            total_domains=total_count,
            domains_at_mil1_or_above=at_mil1_plus,
        )

    total_practices = sum(len(d.practice_ids()) for d in populated_domains)
    if total_practices == 0:
        fraction = 0.0
    else:
        covered = sum(
            round(domain_scores[d.short_code] * len(d.practice_ids())) for d in populated_domains
        )
        fraction = covered / total_practices
    unpopulated_note = (
        f" ({total_count - populated_count} domain(s) not yet transcribed, excluded)"
        if populated_count < total_count
        else ""
    )
    headline = (
        f"{fraction:.0%} of assessable subcategories have accepted evidence{unpopulated_note}."
    )
    return OverallSummary(
        scoring_model=framework.scoring_model,
        headline=headline,
        populated_domains=populated_count,
        total_domains=total_count,
        overall_coverage_fraction=fraction,
    )


def build_dashboard(
    assessment: Assessment,
    framework: FrameworkDefinition,
    evidence_links: list[EvidenceLink],
) -> DashboardReport:
    performed_practice_ids = {
        link.practice_reference
        for link in evidence_links
        if link.review_status in (EvidenceReviewStatus.ACCEPTED, EvidenceReviewStatus.EDITED)
    }
    pending_practice_ids = {
        link.practice_reference
        for link in evidence_links
        if link.review_status == EvidenceReviewStatus.PENDING
    }
    domain_scores = compute_assessment_domain_scores(framework, performed_practice_ids)
    complication = _build_complication(
        framework, performed_practice_ids, pending_practice_ids, domain_scores
    )
    return DashboardReport(
        situation=_build_situation(assessment, framework, evidence_links),
        domain_scores=domain_scores,
        overall=_build_overall_summary(framework, domain_scores),
        complication=complication,
        resolution=_build_resolution(complication),
    )
