"""Executive dashboard: gap analysis and progress tracking (Sprint 6).

Sprint 6 of the two-part Executive Reporting epic (see the
executive-reporting skill's "Example usage" note: Sprint 6 is
dashboard/analytics, Sprint 7 is PDF/XLSX generation — not built here).

Structures a single assessment's current state using the
situation/complication/resolution convention: what was assessed
(situation), where it falls short grouped MECE by domain
(complication), and a prioritized, effort-based gap list (resolution).
Every number carries a templated "so what" sentence, per the skill's
rule against presenting a figure without a business-consequence
sentence attached — templated from real computed values, never
generated by a model, consistent with this project's standing "verified
over fabricated" discipline (this sprint still has no LLM in the loop
at all; see ADR-0011).
"""

from __future__ import annotations

from compliance_platform.models.assessment import (
    Assessment,
    EvidenceLink,
    EvidenceReviewStatus,
    PracticeFinding,
    PracticeFindingStatus,
)
from compliance_platform.models.framework import Domain, FrameworkDefinition
from compliance_platform.models.report import (
    DashboardReport,
    DomainGapGroup,
    EvidenceCitation,
    GapItem,
    OverallSummary,
    ResolutionItem,
    Situation,
)
from compliance_platform.services.scoring_service import compute_assessment_domain_scores

# Findings that override an unmet practice back to "not a gap" if it has
# accepted/edited evidence. PARTIALLY_SATISFIED and NOT_SATISFIED never
# count as performed even with accepted evidence — a reviewer's explicit
# "this isn't (fully) met" judgment overrides a possibly-stale acceptance.
_NEVER_PERFORMED_STATUSES = (
    PracticeFindingStatus.NOT_SATISFIED,
    PracticeFindingStatus.INSUFFICIENT_EVIDENCE,
    PracticeFindingStatus.PARTIALLY_SATISFIED,
)


def performed_and_excluded_practice_ids(
    evidence_links: list[EvidenceLink], findings: list[PracticeFinding]
) -> tuple[set[str], frozenset[str]]:
    """Folds explicit PracticeFinding overrides (ADR-0030) on top of the
    evidence-link-derived "performed" set. A practice with no
    PracticeFinding row behaves exactly as before ADR-0030 (evidence
    alone decides it) — additive, not a breaking change to existing
    assessments. Findings are authoritative where present: SATISFIED
    counts a practice as performed even with no accepted evidence link
    (e.g. a documented compensating control); NOT_SATISFIED,
    INSUFFICIENT_EVIDENCE, or PARTIALLY_SATISFIED removes a practice
    from "performed" even if evidence was once accepted, so a
    reviewer's considered judgment always wins over an earlier,
    possibly-superseded evidence acceptance. NOT_APPLICABLE practices
    are returned separately, for exclusion from scoring denominators
    entirely rather than counting as either performed or a gap.

    Shared by services/assessment_service.py.compute_scores and
    build_dashboard below, so scores and the dashboard's gap list can
    never disagree about which practices are "performed" for a given
    assessment.
    """
    performed_practice_ids = {
        link.practice_reference
        for link in evidence_links
        if link.review_status in (EvidenceReviewStatus.ACCEPTED, EvidenceReviewStatus.EDITED)
    }
    excluded_practice_ids: set[str] = set()
    for finding in findings:
        if finding.status == PracticeFindingStatus.SATISFIED:
            performed_practice_ids.add(finding.practice_reference)
        elif finding.status in _NEVER_PERFORMED_STATUSES:
            performed_practice_ids.discard(finding.practice_reference)
        if finding.status == PracticeFindingStatus.NOT_APPLICABLE:
            excluded_practice_ids.add(finding.practice_reference)
    return performed_practice_ids, frozenset(excluded_practice_ids)


def _build_situation(
    assessment: Assessment,
    framework: FrameworkDefinition,
    evidence_links: list[EvidenceLink],
) -> Situation:
    counts = {status: 0 for status in EvidenceReviewStatus}
    for link in evidence_links:
        counts[link.review_status] += 1
    unpopulated = [d.short_code for d in framework.domains if not d.practices_populated]
    return Situation(
        assessment_id=assessment.id,
        assessment_name=assessment.name,
        framework_name=framework.name,
        scoring_model=framework.scoring_model,
        status=assessment.status.value,
        total_evidence_links=len(evidence_links),
        accepted_count=counts[EvidenceReviewStatus.ACCEPTED],
        edited_count=counts[EvidenceReviewStatus.EDITED],
        rejected_count=counts[EvidenceReviewStatus.REJECTED],
        pending_ai_review_count=counts[EvidenceReviewStatus.PENDING],
        unpopulated_domains=unpopulated,
    )


def _domain_so_what(
    scoring_model: str, domain_full_name: str, met: int, total: int, score: float
) -> str:
    if total == 0:
        return f"{domain_full_name} has no transcribed practices yet and cannot be assessed."
    if met == total:
        return (
            f"{domain_full_name} is fully covered by reviewed evidence "
            f"({met} of {total} practices)."
        )
    if scoring_model == "cumulative_mil":
        if score == 0:
            return (
                f"{domain_full_name} has not yet reached MIL1: {total - met} of {total} "
                "practices still need evidence, blocking any maturity credit for this domain."
            )
        return (
            f"{domain_full_name} is at MIL{int(score)}: {total - met} of {total} practices "
            "still need evidence before the next MIL level is reachable."
        )
    covered_pct = met / total
    return (
        f"{domain_full_name} is at {covered_pct:.0%} coverage: {total - met} of {total} "
        "subcategories still lack accepted evidence."
    )


def _build_complication(
    framework: FrameworkDefinition,
    performed_practice_ids: set[str],
    excluded_practice_ids: frozenset[str],
    pending_practice_ids: set[str],
    domain_scores: dict[str, float],
    findings_by_practice: dict[str, PracticeFinding],
    evidence_links_by_practice: dict[str, list[EvidenceLink]],
) -> list[DomainGapGroup]:
    groups: list[DomainGapGroup] = []
    for domain in framework.domains:
        if not domain.practices_populated:
            continue
        # NOT_APPLICABLE practices (ADR-0030) are excluded entirely —
        # neither a gap nor counted toward this domain's total, the same
        # denominator scoring_service.py's compute_domain_coverage uses.
        applicable_practices = [
            p for p in domain.all_practices() if p.id not in excluded_practice_ids
        ]
        total = len(applicable_practices)
        gaps = []
        for p in applicable_practices:
            if p.id in performed_practice_ids:
                continue
            finding = findings_by_practice.get(p.id)
            gaps.append(
                GapItem(
                    practice_id=p.id,
                    practice_text=p.text,
                    mil=p.mil,
                    has_pending_ai_proposal=p.id in pending_practice_ids,
                    status=finding.status if finding else PracticeFindingStatus.INSUFFICIENT_EVIDENCE,
                    finding_rationale=finding.rationale if finding else None,
                    cited_evidence=[
                        EvidenceCitation(
                            evidence_link_id=link.id,
                            document_id=link.document_id,
                            review_status=link.review_status,
                        )
                        for link in evidence_links_by_practice.get(p.id, [])
                    ],
                )
            )
        if not gaps:
            continue
        gaps.sort(key=lambda g: (g.mil is None, g.mil if g.mil is not None else 0))
        met = total - len(gaps)
        groups.append(
            DomainGapGroup(
                domain_short_code=domain.short_code,
                domain_full_name=domain.full_name,
                total_practices=total,
                met_practices=met,
                gaps=gaps,
                so_what=_domain_so_what(
                    framework.scoring_model,
                    domain.full_name,
                    met,
                    total,
                    domain_scores[domain.short_code],
                ),
            )
        )
    return groups


def _build_resolution(complication: list[DomainGapGroup]) -> list[ResolutionItem]:
    """Sorted by fewest missing practices first — the concrete "quick
    win" framing: a small, closeable gap is the highest-leverage next
    action a reviewer can take, without inventing a fabricated
    business-impact score this project has no basis to assign (see
    ADR-0012).
    """
    ranked = sorted(complication, key=lambda g: len(g.gaps))
    resolution: list[ResolutionItem] = []
    for group in ranked:
        if group.met_practices == 0:
            rationale = (
                f"No evidence yet for this domain; closing {len(group.gaps)} practice(s) "
                "would establish its first maturity credit."
            )
        else:
            rationale = (
                f"Already {group.met_practices} of {group.total_practices} practices met; "
                f"only {len(group.gaps)} remaining to fully close this domain."
            )
        resolution.append(
            ResolutionItem(
                domain_short_code=group.domain_short_code,
                domain_full_name=group.domain_full_name,
                missing_count=len(group.gaps),
                rationale=rationale,
            )
        )
    return resolution


def _build_overall_summary(
    framework: FrameworkDefinition,
    domain_scores: dict[str, float],
    excluded_practice_ids: frozenset[str],
) -> OverallSummary:
    populated_domains = [d for d in framework.domains if d.practices_populated]
    populated_count = len(populated_domains)
    total_count = len(framework.domains)

    if framework.scoring_model == "cumulative_mil":
        at_mil1_plus = sum(1 for d in populated_domains if domain_scores[d.short_code] >= 1.0)
        unpopulated_note = (
            f" ({total_count - populated_count} domain(s) not yet transcribed into the "
            "platform's schema, excluded from this count)"
            if populated_count < total_count
            else ""
        )
        headline = (
            f"{at_mil1_plus} of {populated_count} assessable domains have reached MIL1 or "
            f"higher{unpopulated_note}."
        )
        return OverallSummary(
            scoring_model=framework.scoring_model,
            headline=headline,
            populated_domains=populated_count,
            total_domains=total_count,
            domains_at_mil1_or_above=at_mil1_plus,
        )

    # ADR-0030: weight each domain by its applicable (non-NOT_APPLICABLE)
    # practice count, the same denominator compute_domain_coverage used
    # to produce domain_scores — otherwise this weighted average would
    # silently disagree with the per-domain numbers it's built from.
    def _applicable_count(d: Domain) -> int:
        return len(d.practice_ids() - excluded_practice_ids)

    total_practices = sum(_applicable_count(d) for d in populated_domains)
    if total_practices == 0:
        fraction = 0.0
    else:
        covered = sum(
            round(domain_scores[d.short_code] * _applicable_count(d)) for d in populated_domains
        )
        fraction = covered / total_practices
    unpopulated_note = (
        f" ({total_count - populated_count} domain(s) not yet transcribed, excluded)"
        if populated_count < total_count
        else ""
    )
    headline = (
        f"{fraction:.0%} of assessable subcategories have accepted evidence{unpopulated_note}."
    )
    return OverallSummary(
        scoring_model=framework.scoring_model,
        headline=headline,
        populated_domains=populated_count,
        total_domains=total_count,
        overall_coverage_fraction=fraction,
    )


def build_dashboard(
    assessment: Assessment,
    framework: FrameworkDefinition,
    evidence_links: list[EvidenceLink],
    findings: list[PracticeFinding] | None = None,
) -> DashboardReport:
    findings = findings if findings is not None else []
    performed_practice_ids, excluded_practice_ids = performed_and_excluded_practice_ids(
        evidence_links, findings
    )
    pending_practice_ids = {
        link.practice_reference
        for link in evidence_links
        if link.review_status == EvidenceReviewStatus.PENDING
    }
    domain_scores = compute_assessment_domain_scores(
        framework, performed_practice_ids, excluded_practice_ids
    )
    findings_by_practice = {f.practice_reference: f for f in findings}
    evidence_links_by_practice: dict[str, list[EvidenceLink]] = {}
    for link in evidence_links:
        evidence_links_by_practice.setdefault(link.practice_reference, []).append(link)
    complication = _build_complication(
        framework,
        performed_practice_ids,
        excluded_practice_ids,
        pending_practice_ids,
        domain_scores,
        findings_by_practice,
        evidence_links_by_practice,
    )
    return DashboardReport(
        situation=_build_situation(assessment, framework, evidence_links),
        domain_scores=domain_scores,
        overall=_build_overall_summary(framework, domain_scores, excluded_practice_ids),
        complication=complication,
        resolution=_build_resolution(complication),
    )
