/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Document */
        post: operations["ingest_document_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assessments */
        get: operations["list_assessments_assessments_get"];
        put?: never;
        /** Create Assessment */
        post: operations["create_assessment_assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment */
        get: operations["get_assessment_assessments__assessment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Status */
        post: operations["transition_status_assessments__assessment_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/status-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status History */
        get: operations["get_status_history_assessments__assessment_id__status_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_assessments__assessment_id__evidence_get"];
        put?: never;
        /** Link Evidence */
        post: operations["link_evidence_assessments__assessment_id__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scores
         * @description Per-domain score. Meaning depends on the assessment's framework —
         *     check GET /frameworks/{name}'s scoring_model field: "cumulative_mil"
         *     means a whole-number MIL 0-3 (C2M2); "coverage" means a 0.0-1.0
         *     fraction of subcategories with evidence (NIST CSF 2.0, which has no
         *     native maturity concept — see ADR-0010). A domain not yet
         *     transcribed into framework_mapping/ always reports 0/0.0, not an
         *     error — see Domain.practices_populated.
         */
        get: operations["get_scores_assessments__assessment_id__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Executive dashboard (Sprint 6): situation/complication/resolution
         *     view of this assessment — see services/report_service.py and
         *     ADR-0012. No LLM narrative generation; every figure is computed
         *     directly from real evidence links and the framework's structured
         *     schema.
         */
        get: operations["get_dashboard_assessments__assessment_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/report/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Pdf
         * @description PDF rendering of the same dashboard GET /dashboard returns
         *     (Sprint 7) — see services/export_service.py and ADR-0013. Same
         *     error mapping as the dashboard endpoint, since both are built from
         *     the same DashboardReport.
         */
        get: operations["get_dashboard_pdf_assessments__assessment_id__report_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/report/xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Xlsx
         * @description XLSX rendering of the same dashboard GET /dashboard returns
         *     (Sprint 7) — see services/export_service.py and ADR-0013.
         */
        get: operations["get_dashboard_xlsx_assessments__assessment_id__report_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/evidence/{evidence_link_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Evidence
         * @description Applies a human accept/edit/reject decision to a pending evidence
         *     link — see services/assessment_service.py.review_evidence and the
         *     assessment-generation skill's human-in-the-loop invariant. Only
         *     ValueError (a missing corrected_practice_reference on an "edited"
         *     decision) is caught here — every other exception this can raise is
         *     handled globally, see api/error_handlers.py.
         */
        post: operations["review_evidence_assessments__assessment_id__evidence__evidence_link_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/propose-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose Mappings
         * @description Runs the retrieval-based mapping engine (services/mapping_service.py,
         *     ADR-0011) and persists any resulting proposals as AI-proposed,
         *     pending-review evidence links — always over documents already
         *     associated with this assessment, never the whole vector store.
         */
        post: operations["propose_mappings_assessments__assessment_id__propose_mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat With Assessment
         * @description Retrieval-only Q&A over this assessment's reviewed evidence
         *     (Sprint 8) — see services/chat_service.py and ADR-0014. Returns
         *     ranked, cited evidence chunks; nothing here is model-generated, so
         *     an empty result list (no reviewed evidence, or nothing above the
         *     similarity threshold) is a valid 200 response, not an error.
         */
        post: operations["chat_with_assessment_assessments__assessment_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frameworks/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Framework */
        get: operations["get_framework_frameworks__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Assessment
         * @description A single compliance assessment instance.
         *
         *     framework_name is a free-text label (e.g. "C2M2") in Sprint 2 — not
         *     yet validated against a structured framework schema, since
         *     framework_mapping/ data does not exist until Sprint 3-4. See
         *     services/assessment_service.py and the framework-mapping skill.
         */
        Assessment: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Framework Name */
            framework_name: string;
            /** @default draft */
            status: components["schemas"]["AssessmentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * AssessmentStatus
         * @enum {string}
         */
        AssessmentStatus: "draft" | "in_review" | "finalized";
        /**
         * AssessmentStatusChange
         * @description Audit trail of every status transition an assessment goes through
         *     — the "state tracking" half of Sprint 2's scope, distinct from the
         *     evidence-to-score audit trail EvidenceLink provides. Directly serves
         *     the Internal Audit stakeholder in PROJECT_CHARTER.md's Stakeholder Map.
         */
        AssessmentStatusChange: {
            /** Id */
            id?: string;
            /** Assessment Id */
            assessment_id: string;
            from_status?: components["schemas"]["AssessmentStatus"] | null;
            to_status: components["schemas"]["AssessmentStatus"];
            /** Note */
            note?: string | null;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at?: string;
        };
        /** Body_ingest_document_ingest_post */
        Body_ingest_document_ingest_post: {
            /** File */
            file: string;
            /** Submitter */
            submitter?: string | null;
        };
        /** ChatQuestionRequest */
        ChatQuestionRequest: {
            /** Question */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Question */
            question: string;
            /** Results */
            results: components["schemas"]["ChatResult"][];
        };
        /** ChatResult */
        ChatResult: {
            /** Practice Reference */
            practice_reference: string;
            /** Document Id */
            document_id: string;
            /** Chunk Id */
            chunk_id: string;
            /** Similarity */
            similarity: number;
            /** Chunk Text */
            chunk_text: string;
        };
        /** CreateAssessmentRequest */
        CreateAssessmentRequest: {
            /** Name */
            name: string;
            /** Framework Name */
            framework_name: string;
        };
        /** DashboardReport */
        DashboardReport: {
            situation: components["schemas"]["Situation"];
            /** Domain Scores */
            domain_scores: {
                [key: string]: number;
            };
            overall: components["schemas"]["OverallSummary"];
            /** Complication */
            complication: components["schemas"]["DomainGapGroup"][];
            /** Resolution */
            resolution: components["schemas"]["ResolutionItem"][];
        };
        /** Domain */
        Domain: {
            /** Short Code */
            short_code: string;
            /** Full Name */
            full_name: string;
            /** Purpose */
            purpose: string;
            /** Practices Populated */
            practices_populated: boolean;
            /** Objectives */
            objectives: components["schemas"]["Objective"][];
            /**
             * Source Version
             * @default
             */
            source_version: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
        };
        /**
         * DomainGapGroup
         * @description One MECE group in the "complication" section — one entry per
         *     domain with at least one unmet practice, plus a templated "so what"
         *     sentence per the executive-reporting skill's rule that no number
         *     appears without a business-consequence sentence attached. The
         *     sentence is assembled from real, computed values, never generated
         *     by a model — see ADR-0012.
         */
        DomainGapGroup: {
            /** Domain Short Code */
            domain_short_code: string;
            /** Domain Full Name */
            domain_full_name: string;
            /** Total Practices */
            total_practices: number;
            /** Met Practices */
            met_practices: number;
            /** Gaps */
            gaps: components["schemas"]["GapItem"][];
            /** So What */
            so_what: string;
        };
        /**
         * Equivalent
         * @description One reviewed, deliberately-curated cross-framework equivalence
         *     (Sprint 10, US-5.2/FR-14 — see ADR-0019). Populated by
         *     services/framework_loader.py from framework_mapping/
         *     cross_framework_equivalence.yaml, never hand-constructed elsewhere —
         *     per the framework-mapping skill, equivalence is additive and
         *     human-reviewed, not inferred by embedding similarity alone, so
         *     `similarity` is disclosed context for a judgment already made, not
         *     the basis for accepting this pairing at request time.
         */
        Equivalent: {
            /** Framework Name */
            framework_name: string;
            /** Practice Id */
            practice_id: string;
            /** Practice Text */
            practice_text: string;
            /** Similarity */
            similarity: number;
            /** Rationale */
            rationale: string;
        };
        /**
         * EvidenceLink
         * @description Associates an ingested document (Sprint 1, identified by
         *     document_id from the vector store) with an assessment and a practice
         *     reference.
         *
         *     practice_reference is free text in Sprint 2 (e.g. "AM-1a") — becomes
         *     a real foreign key into framework_mapping/ once that data exists
         *     (Sprint 3+). Implements the assessment-generation skill's core
         *     invariant — no score exists without a linked evidence trail —
         *     enforced structurally by services/assessment_service.py, which
         *     refuses to create a link whose document_id was never actually
         *     ingested into the vector store.
         */
        EvidenceLink: {
            /** Id */
            id?: string;
            /** Assessment Id */
            assessment_id: string;
            /** Document Id */
            document_id: string;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Practice Reference */
            practice_reference: string;
            /** Note */
            note?: string | null;
            /** @default manual */
            source: components["schemas"]["EvidenceSource"];
            /** @default accepted */
            review_status: components["schemas"]["EvidenceReviewStatus"];
            /** Confidence */
            confidence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Reviewed At */
            reviewed_at?: string | null;
        };
        /**
         * EvidenceReviewStatus
         * @enum {string}
         */
        EvidenceReviewStatus: "pending" | "accepted" | "edited" | "rejected";
        /**
         * EvidenceSource
         * @enum {string}
         */
        EvidenceSource: "manual" | "ai_proposed";
        /** FrameworkDefinition */
        FrameworkDefinition: {
            /** Name */
            name: string;
            /** Full Name */
            full_name: string;
            /** Version */
            version: string;
            /** Source Title */
            source_title: string;
            /** Source Publisher */
            source_publisher: string;
            /** Source Date */
            source_date: string;
            /** Source Url */
            source_url: string;
            /** Retrieved Date */
            retrieved_date: string;
            /** Total Practices In Source */
            total_practices_in_source: number;
            /**
             * Scoring Model
             * @enum {string}
             */
            scoring_model: "cumulative_mil" | "coverage";
            /**
             * Mil Levels
             * @default []
             */
            mil_levels: components["schemas"]["MilLevelDefinition"][];
            /** Scoring Note */
            scoring_note: string;
            /** Domains */
            domains: components["schemas"]["Domain"][];
        };
        /** GapItem */
        GapItem: {
            /** Practice Id */
            practice_id: string;
            /** Practice Text */
            practice_text: string;
            /** Mil */
            mil?: number | null;
            /**
             * Has Pending Ai Proposal
             * @default false
             */
            has_pending_ai_proposal: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionResult
         * @description Returned by the ingestion API and service layer.
         */
        IngestionResult: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            parse_status: components["schemas"]["ParseStatus"];
            /** Parse Warnings */
            parse_warnings?: string[];
            /** Chunk Count */
            chunk_count: number;
            /** Embedding Backend */
            embedding_backend: string;
        };
        /** LinkEvidenceRequest */
        LinkEvidenceRequest: {
            /** Document Id */
            document_id: string;
            /** Practice Reference */
            practice_reference: string;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Note */
            note?: string | null;
            /** @default manual */
            source: components["schemas"]["EvidenceSource"];
        };
        /** MilLevelDefinition */
        MilLevelDefinition: {
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** Objective */
        Objective: {
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Practices */
            practices: components["schemas"]["Practice"][];
            /**
             * Purpose
             * @default
             */
            purpose: string;
        };
        /**
         * OverallSummary
         * @description Deliberately does NOT average domain scores across a
         *     cumulative_mil framework — MIL is an ordinal scale (see
         *     c2m2-expert skill), and averaging ordinal values into a single
         *     number would misrepresent it exactly the way R-15 in the risk
         *     register warns against. cumulative_mil frameworks get a
         *     count-based headline instead; coverage frameworks, whose per-domain
         *     scores are already true fractions, get a legitimate weighted
         *     average. See ADR-0012.
         */
        OverallSummary: {
            /** Scoring Model */
            scoring_model: string;
            /** Headline */
            headline: string;
            /** Populated Domains */
            populated_domains: number;
            /** Total Domains */
            total_domains: number;
            /** Domains At Mil1 Or Above */
            domains_at_mil1_or_above?: number | null;
            /** Overall Coverage Fraction */
            overall_coverage_fraction?: number | null;
        };
        /**
         * ParseStatus
         * @enum {string}
         */
        ParseStatus: "success" | "unsupported_scanned" | "encoding_failure" | "empty" | "failed";
        /** Practice */
        Practice: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Mil */
            mil?: number | null;
            /**
             * Equivalents
             * @default []
             */
            equivalents: components["schemas"]["Equivalent"][];
            /**
             * Applicability
             * @default
             */
            applicability: string;
        };
        /**
         * ResolutionItem
         * @description One entry in the prioritized gap list. Prioritization is
         *     effort-based (fewest missing practices first within a tier), not a
         *     fabricated impact score — see ADR-0012 for why "quick wins" (small,
         *     concrete, closeable gaps) is the honest framing this project can
         *     support without inventing a business-impact number it cannot back.
         */
        ResolutionItem: {
            /** Domain Short Code */
            domain_short_code: string;
            /** Domain Full Name */
            domain_full_name: string;
            /** Missing Count */
            missing_count: number;
            /** Rationale */
            rationale: string;
        };
        /** ReviewEvidenceRequest */
        ReviewEvidenceRequest: {
            decision: components["schemas"]["EvidenceReviewStatus"];
            /** Corrected Practice Reference */
            corrected_practice_reference?: string | null;
            /** Note */
            note?: string | null;
        };
        /** Situation */
        Situation: {
            /** Assessment Id */
            assessment_id: string;
            /** Assessment Name */
            assessment_name: string;
            /** Framework Name */
            framework_name: string;
            /** Scoring Model */
            scoring_model: string;
            /** Status */
            status: string;
            /** Total Evidence Links */
            total_evidence_links: number;
            /** Accepted Count */
            accepted_count: number;
            /** Edited Count */
            edited_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Pending Ai Review Count */
            pending_ai_review_count: number;
            /** Unpopulated Domains */
            unpopulated_domains: string[];
        };
        /** StatusTransitionRequest */
        StatusTransitionRequest: {
            status: components["schemas"]["AssessmentStatus"];
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_document_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_document_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessments_assessments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"][];
                };
            };
        };
    };
    create_assessment_assessments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssessmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_status_assessments__assessment_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_history_assessments__assessment_id__status_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentStatusChange"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_assessments__assessment_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLink"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_evidence_assessments__assessment_id__evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scores_assessments__assessment_id__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_assessments__assessment_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_pdf_assessments__assessment_id__report_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_xlsx_assessments__assessment_id__report_xlsx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_evidence_assessments__assessment_id__evidence__evidence_link_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
                evidence_link_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_mappings_assessments__assessment_id__propose_mappings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLink"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_with_assessment_assessments__assessment_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_framework_frameworks__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
