/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Document */
        post: operations["ingest_document_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Document Async
         * @description Queue a document and return immediately with a job to poll.
         *
         *     The synchronous POST /ingest above is unchanged and still correct
         *     for small documents. This exists because that one holds the request
         *     open for the whole parse/chunk/embed pass, which a large or scanned
         *     document can push past the proxy's read ceiling -- returning a
         *     gateway timeout that is indistinguishable from a rejection and
         *     leaves no record the work ever started.
         *
         *     202 rather than 201: nothing has been created yet at this point
         *     except the intent to try.
         */
        post: operations["ingest_document_async_ingest_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestion Jobs */
        get: operations["list_ingestion_jobs_ingest_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Job */
        get: operations["get_ingestion_job_ingest_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assessments */
        get: operations["list_assessments_assessments_get"];
        put?: never;
        /** Create Assessment */
        post: operations["create_assessment_assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment */
        get: operations["get_assessment_assessments__assessment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Status */
        post: operations["transition_status_assessments__assessment_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/finalization-readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Finalization Readiness
         * @description Whether this assessment may be finalized, and what blocks it
         *     (ADR-0058).
         *
         *     Blockers are machine-readable categories with the affected ids, so
         *     the UI renders a checklist and disables its button without parsing
         *     English. The same function backs the server-side gate in
         *     transition_status — this endpoint reports the rule, it does not
         *     define a second one.
         */
        get: operations["get_finalization_readiness_assessments__assessment_id__finalization_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Seal
         * @description Check a finalized assessment against the seal written when it was
         *     finalized (R-12).
         *
         *     Answers the question an auditor asks about a compliance record:
         *     not "can your software edit this?" but "can you show nothing did?"
         *     The stored and recomputed digests are both returned, so anyone
         *     holding an exported report can compare its printed seal against
         *     this without trusting the verdict field.
         *
         *     Deliberately a plain 200 for every outcome, including ALTERED. A
         *     non-2xx would make a detected alteration look like a failure to
         *     answer, and this endpoint answering successfully is exactly what a
         *     detected alteration IS.
         */
        get: operations["verify_seal_assessments__assessment_id__verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/status-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status History */
        get: operations["get_status_history_assessments__assessment_id__status_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_assessments__assessment_id__evidence_get"];
        put?: never;
        /** Link Evidence */
        post: operations["link_evidence_assessments__assessment_id__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scores
         * @description Per-domain score. Meaning depends on the assessment's framework —
         *     check GET /frameworks/{name}'s scoring_model field: "cumulative_mil"
         *     means a whole-number MIL 0-3 (C2M2); "coverage" means a 0.0-1.0
         *     fraction of subcategories with evidence (NIST CSF 2.0, which has no
         *     native maturity concept — see ADR-0010). A domain not yet
         *     transcribed into framework_mapping/ always reports 0/0.0, not an
         *     error — see Domain.practices_populated.
         */
        get: operations["get_scores_assessments__assessment_id__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Executive dashboard (Sprint 6): situation/complication/resolution
         *     view of this assessment — see services/report_service.py and
         *     ADR-0012. No LLM narrative generation; every figure is computed
         *     directly from real evidence links and the framework's structured
         *     schema.
         */
        get: operations["get_dashboard_assessments__assessment_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/report/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Pdf
         * @description PDF rendering of the same dashboard GET /dashboard returns
         *     (Sprint 7) — see services/export_service.py and ADR-0013. Same
         *     error mapping as the dashboard endpoint, since both are built from
         *     the same DashboardReport. sanitized=true (ADR-0032) requires a
         *     current, matching PracticeFinding/evidence-state approval recorded
         *     via POST .../sanitization/approve first — see
         *     services/assessment_service.py.
         */
        get: operations["get_dashboard_pdf_assessments__assessment_id__report_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/report/xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Xlsx
         * @description XLSX rendering of the same dashboard GET /dashboard returns
         *     (Sprint 7) — see services/export_service.py and ADR-0013. See
         *     get_dashboard_pdf's docstring for the sanitized=true behavior.
         */
        get: operations["get_dashboard_xlsx_assessments__assessment_id__report_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/sanitization/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Sanitization
         * @description Read-only preview/diff of what a sanitized export would redact
         *     or pseudonymize (ADR-0032) — never persisted, never itself
         *     authorizes an export. custom_terms is the reviewer-supplied list of
         *     organization-specific identifiers (names, facility/vendor/customer/
         *     employee identifiers) to pseudonymize; see
         *     services/sanitization_service.py for why those categories can't be
         *     detected automatically without fabricating an NER capability this
         *     project hasn't evaluated.
         */
        post: operations["preview_sanitization_assessments__assessment_id__sanitization_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/sanitization/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Sanitization
         * @description Records explicit human approval of one specific sanitized report
         *     (ADR-0032's "never silently publish an AI-sanitized report" rule).
         *     Required before GET .../report/pdf|xlsx?sanitized=true will
         *     succeed; a later change to the underlying report invalidates this
         *     approval automatically (see SanitizationApprovalStaleError).
         */
        post: operations["approve_sanitization_assessments__assessment_id__sanitization_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/evidence/{evidence_link_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Evidence
         * @description Applies a human accept/edit/reject decision to a pending evidence
         *     link — see services/assessment_service.py.review_evidence and the
         *     assessment-generation skill's human-in-the-loop invariant. Only
         *     ValueError (a missing corrected_practice_reference on an "edited"
         *     decision) is caught here — every other exception this can raise is
         *     handled globally, see api/error_handlers.py.
         */
        post: operations["review_evidence_assessments__assessment_id__evidence__evidence_link_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/practice-findings/{practice_reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Practice Finding
         * @description Records a reviewer's explicit compliance judgment for one
         *     practice — SATISFIED, PARTIALLY_SATISFIED, NOT_SATISFIED,
         *     INSUFFICIENT_EVIDENCE, or NOT_APPLICABLE (ADR-0030). PUT, not POST:
         *     idempotent upsert of the single current finding for this
         *     (assessment, practice) pair, not a growing list of independent
         *     records — see services/assessment_service.py.set_practice_finding
         *     and PracticeFindingChange for the append-only history this still
         *     preserves underneath.
         */
        put: operations["set_practice_finding_assessments__assessment_id__practice_findings__practice_reference__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/practice-findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Practice Findings */
        get: operations["list_practice_findings_assessments__assessment_id__practice_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/practice-findings/{practice_reference}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice Finding History */
        get: operations["get_practice_finding_history_assessments__assessment_id__practice_findings__practice_reference__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/practice-findings/{practice_reference}/evidence-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request More Evidence
         * @description Records a reviewer's explicit request that someone go find and
         *     upload more evidence for this practice (ADR-0043) — a workflow
         *     action distinct from set_practice_finding's compliance judgment;
         *     the two can coexist for the same practice. POST, not PUT: each call
         *     creates a new request, not an idempotent upsert of a single current
         *     one — multiple open requests can exist for the same practice.
         */
        post: operations["request_more_evidence_assessments__assessment_id__practice_findings__practice_reference__evidence_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/evidence-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Requests */
        get: operations["list_evidence_requests_assessments__assessment_id__evidence_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/evidence-requests/{request_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Evidence Request
         * @description Marks an evidence request resolved. Always explicit -- never
         *     inferred from a new evidence link being added, since linking
         *     evidence doesn't guarantee it actually addresses what was
         *     requested.
         */
        post: operations["resolve_evidence_request_assessments__assessment_id__evidence_requests__request_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/propose-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose Mappings
         * @description Runs the retrieval-based mapping engine (services/mapping_service.py,
         *     ADR-0011) and persists any resulting proposals as AI-proposed,
         *     pending-review evidence links — always over documents already
         *     associated with this assessment, never the whole vector store.
         */
        post: operations["propose_mappings_assessments__assessment_id__propose_mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat With Assessment
         * @description Retrieval-only Q&A over this assessment's reviewed evidence
         *     (Sprint 8) — see services/chat_service.py and ADR-0014. Returns
         *     ranked, cited evidence chunks; nothing here is model-generated, so
         *     an empty result list (no reviewed evidence, or nothing above the
         *     similarity threshold) is a valid 200 response, not an error.
         */
        post: operations["chat_with_assessment_assessments__assessment_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frameworks/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Framework
         * @description version (Sprint 18, ADR-0053): browse a SPECIFIC loaded version of
         *     this framework, if the registry has more than one — omit for
         *     whatever's currently latest, matching this endpoint's pre-ADR-0053
         *     behavior exactly.
         */
        get: operations["get_framework_frameworks__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frameworks/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Framework Versions
         * @description Every version this registry knows about for `name` (Sprint 18,
         *     ADR-0053), so a caller can discover what's actually available to
         *     pass to ?version= above (or to CreateAssessmentRequest.framework_version)
         *     without guessing. [] for an unrecognized name, never a 404 — an
         *     empty list of versions is itself the honest, correct answer.
         */
        get: operations["get_framework_versions_frameworks__name__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description Every ingested document, newest first.
         *
         *     Declared BEFORE /{document_id} because FastAPI matches routes in
         *     declaration order; an empty path is unambiguous here, but keeping
         *     the literal route above the parameterised one is the habit that
         *     stops a future literal route (e.g. /recent) being swallowed as a
         *     document id.
         */
        get: operations["list_documents_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveSanitizationRequest */
        ApproveSanitizationRequest: {
            /**
             * Custom Terms
             * @default []
             */
            custom_terms: string[];
            /** Approved By */
            approved_by: string;
        };
        /**
         * Assessment
         * @description A single compliance assessment instance.
         *
         *     framework_name is a free-text label (e.g. "C2M2") in Sprint 2 — not
         *     yet validated against a structured framework schema, since
         *     framework_mapping/ data does not exist until Sprint 3-4. See
         *     services/assessment_service.py and the framework-mapping skill.
         */
        Assessment: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Framework Name */
            framework_name: string;
            /** Framework Version */
            framework_version?: string | null;
            /** @default draft */
            status: components["schemas"]["AssessmentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Sealed Digest */
            sealed_digest?: string | null;
            /** Sealed At */
            sealed_at?: string | null;
            /** Seal Version */
            seal_version?: string | null;
        };
        /**
         * AssessmentStatus
         * @enum {string}
         */
        AssessmentStatus: "draft" | "in_review" | "finalized";
        /**
         * AssessmentStatusChange
         * @description Audit trail of every status transition an assessment goes through
         *     — the "state tracking" half of Sprint 2's scope, distinct from the
         *     evidence-to-score audit trail EvidenceLink provides. Directly serves
         *     the Internal Audit stakeholder in PROJECT_CHARTER.md's Stakeholder Map.
         */
        AssessmentStatusChange: {
            /** Id */
            id?: string;
            /** Assessment Id */
            assessment_id: string;
            from_status?: components["schemas"]["AssessmentStatus"] | null;
            to_status: components["schemas"]["AssessmentStatus"];
            /** Note */
            note?: string | null;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at?: string;
            /** Actor */
            actor?: string | null;
        };
        /** Body_ingest_document_async_ingest_async_post */
        Body_ingest_document_async_ingest_async_post: {
            /** File */
            file: string;
            /** Submitter */
            submitter?: string | null;
            /** Supersedes Document Id */
            supersedes_document_id?: string | null;
        };
        /** Body_ingest_document_ingest_post */
        Body_ingest_document_ingest_post: {
            /** File */
            file: string;
            /** Submitter */
            submitter?: string | null;
            /** Supersedes Document Id */
            supersedes_document_id?: string | null;
        };
        /** ChatQuestionRequest */
        ChatQuestionRequest: {
            /** Question */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Question */
            question: string;
            /** Results */
            results: components["schemas"]["ChatResult"][];
        };
        /** ChatResult */
        ChatResult: {
            /** Practice Reference */
            practice_reference: string;
            /** Document Id */
            document_id: string;
            /** Chunk Id */
            chunk_id: string;
            /** Similarity */
            similarity: number;
            /** Chunk Text */
            chunk_text: string;
        };
        /** CreateAssessmentRequest */
        CreateAssessmentRequest: {
            /** Name */
            name: string;
            /** Framework Name */
            framework_name: string;
            /** Framework Version */
            framework_version?: string | null;
        };
        /** DashboardReport */
        DashboardReport: {
            situation: components["schemas"]["Situation"];
            /** Domain Scores */
            domain_scores: {
                [key: string]: number;
            };
            overall: components["schemas"]["OverallSummary"];
            /** Complication */
            complication: components["schemas"]["DomainGapGroup"][];
            /** Resolution */
            resolution: components["schemas"]["ResolutionItem"][];
        };
        /**
         * DocumentDetail
         * @description Document versioning (Sprint 18, ADR-0039): the durable record of
         *     one ingested document, plus the reverse lookup a reviewer actually
         *     needs -- "has this document since been superseded by a newer
         *     upload?" -- computed at read time, not stored (only the forward
         *     supersedes_document_id declaration is stored, on the newer document).
         */
        DocumentDetail: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** File Type */
            file_type: string;
            /** Content Hash */
            content_hash: string;
            /** Submitter */
            submitter?: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Supersedes Document Id */
            supersedes_document_id?: string | null;
            /** Superseded By Document Id */
            superseded_by_document_id?: string | null;
            /** Parser Version */
            parser_version: string;
        };
        /**
         * DocumentSummary
         * @description One row in a list of ingested documents — what a chooser needs to
         *     let a reviewer recognise a document, and nothing more.
         *
         *     Separate from DocumentDetail rather than reusing it: the list is
         *     resolved with a BULK supersession lookup that answers "is this
         *     superseded" without identifying the superseding document, so this
         *     carries an honest `is_superseded` boolean instead of a
         *     `superseded_by_document_id` that could only be filled with a
         *     placeholder. content_hash is omitted too — it identifies a document
         *     to a machine, not to a human picking one off a list.
         */
        DocumentSummary: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** File Type */
            file_type: string;
            /** Submitter */
            submitter?: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /**
             * Is Superseded
             * @default false
             */
            is_superseded: boolean;
            /** Parser Version */
            parser_version: string;
        };
        /** Domain */
        Domain: {
            /** Short Code */
            short_code: string;
            /** Full Name */
            full_name: string;
            /** Purpose */
            purpose: string;
            /** Practices Populated */
            practices_populated: boolean;
            /** Objectives */
            objectives: components["schemas"]["Objective"][];
            /**
             * Source Version
             * @default
             */
            source_version: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
        };
        /**
         * DomainGapGroup
         * @description One MECE group in the "complication" section — one entry per
         *     domain with at least one unmet practice, plus a templated "so what"
         *     sentence per the executive-reporting skill's rule that no number
         *     appears without a business-consequence sentence attached. The
         *     sentence is assembled from real, computed values, never generated
         *     by a model — see ADR-0012.
         */
        DomainGapGroup: {
            /** Domain Short Code */
            domain_short_code: string;
            /** Domain Full Name */
            domain_full_name: string;
            /** Total Practices */
            total_practices: number;
            /** Met Practices */
            met_practices: number;
            /** Gaps */
            gaps: components["schemas"]["GapItem"][];
            /** So What */
            so_what: string;
        };
        /**
         * Equivalent
         * @description One reviewed, deliberately-curated cross-framework equivalence
         *     (Sprint 10, US-5.2/FR-14 — see ADR-0019). Populated by
         *     services/framework_loader.py from framework_mapping/
         *     cross_framework_equivalence.yaml, never hand-constructed elsewhere —
         *     per the framework-mapping skill, equivalence is additive and
         *     human-reviewed, not inferred by embedding similarity alone, so
         *     `similarity` is disclosed context for a judgment already made, not
         *     the basis for accepting this pairing at request time.
         */
        Equivalent: {
            /** Framework Name */
            framework_name: string;
            /** Practice Id */
            practice_id: string;
            /** Practice Text */
            practice_text: string;
            /** Similarity */
            similarity: number;
            /** Rationale */
            rationale: string;
        };
        /**
         * EvidenceCitation
         * @description One evidence link cited by a GapItem (Sprint 18, ADR-0040) —
         *     "which specific evidence was reviewed and found insufficient",
         *     closing a real, confirmed gap: a gap previously referenced only a
         *     practice, never the evidence trail behind its status/rationale.
         *     Deliberately IDs and status only, never the link's own `note` (which
         *     for an AI-proposed link embeds a quoted evidence-chunk snippet) or
         *     any chunk text — the dashboard has never shown raw evidence text
         *     anywhere else, and this citation shouldn't become the first place
         *     it does, especially since it isn't covered by the sanitization
         *     pipeline's redaction scope (ADR-0032 only ever touches
         *     Situation.assessment_name and GapItem.finding_rationale).
         */
        EvidenceCitation: {
            /** Evidence Link Id */
            evidence_link_id: string;
            /** Document Id */
            document_id: string;
            review_status: components["schemas"]["EvidenceReviewStatus"];
            /**
             * Is Superseded
             * @default false
             */
            is_superseded: boolean;
        };
        /**
         * EvidenceLink
         * @description Associates an ingested document (Sprint 1, identified by
         *     document_id from the vector store) with an assessment and a practice
         *     reference.
         *
         *     practice_reference is free text in Sprint 2 (e.g. "AM-1a") — becomes
         *     a real foreign key into framework_mapping/ once that data exists
         *     (Sprint 3+). Implements the assessment-generation skill's core
         *     invariant — no score exists without a linked evidence trail —
         *     enforced structurally by services/assessment_service.py, which
         *     refuses to create a link whose document_id was never actually
         *     ingested into the vector store.
         */
        EvidenceLink: {
            /** Id */
            id?: string;
            /** Assessment Id */
            assessment_id: string;
            /** Document Id */
            document_id: string;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Practice Reference */
            practice_reference: string;
            /** Original Practice Reference */
            original_practice_reference?: string | null;
            /** Note */
            note?: string | null;
            /** @default manual */
            source: components["schemas"]["EvidenceSource"];
            /** @default accepted */
            review_status: components["schemas"]["EvidenceReviewStatus"];
            /** Confidence */
            confidence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
        };
        /**
         * EvidenceRequest
         * @description A reviewer's explicit request that someone go find and upload
         *     MORE evidence for a specific practice (Sprint 18, ADR-0043) —
         *     distinct from PracticeFindingStatus.INSUFFICIENT_EVIDENCE, which is
         *     a compliance JUDGMENT (this project's own visible reading of the
         *     evidence gathered so far). A request is a WORKFLOW action directed
         *     at a person (frequently Sam, the OT engineering contributor persona
         *     who submits evidence but doesn't judge compliance) — "please go get
         *     X" — and can coexist with any PracticeFindingStatus, including
         *     PARTIALLY_SATISFIED ("this is good enough to note partial credit,
         *     but I still want more to fully confirm it").
         *
         *     Unlike PracticeFinding, no separate append-only history table:
         *     a request's lifecycle is a simple open -> resolved transition, not
         *     a repeatedly-mutating judgment, so resolved_at/resolved_by directly
         *     on this row is itself the complete audit record. Multiple open
         *     requests can exist for the same practice (no uniqueness constraint)
         *     — a real, disclosed simplification, not an oversight: enforcing
         *     "at most one open request per practice" would need to define what
         *     happens to an already-open request when a second is filed, and
         *     nothing in this feature's actual use case requires that.
         *
         *     Resolution is always explicit, never inferred from a new evidence
         *     link being added — linking evidence doesn't guarantee it actually
         *     addresses what was requested, the same "nothing silently automatic"
         *     discipline every other human-in-the-loop decision in this project
         *     already follows (PracticeFinding, SanitizationApproval).
         */
        EvidenceRequest: {
            /** Id */
            id?: string;
            /** Assessment Id */
            assessment_id: string;
            /** Practice Reference */
            practice_reference: string;
            /** Note */
            note: string;
            /** Requested By */
            requested_by: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at?: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolved By */
            resolved_by?: string | null;
        };
        /**
         * EvidenceReviewStatus
         * @enum {string}
         */
        EvidenceReviewStatus: "pending" | "accepted" | "edited" | "rejected";
        /**
         * EvidenceSource
         * @enum {string}
         */
        EvidenceSource: "manual" | "ai_proposed";
        /**
         * FinalizationBlocker
         * @description One reason finalization is blocked, with the specific items to fix.
         *
         *     `affected_ids` holds evidence-link ids, evidence-request ids or
         *     practice references depending on the category — whichever the
         *     reviewer needs to act on. It is capped by the service so a pathological
         *     assessment cannot return an unbounded response body; `count` is always
         *     the true total, so a caller can tell "3 of 300" from "3 of 3".
         */
        FinalizationBlocker: {
            category: components["schemas"]["FinalizationBlockerCategory"];
            /** Count */
            count: number;
            /**
             * Affected Ids
             * @default []
             */
            affected_ids: string[];
            /** Summary */
            summary: string;
        };
        /**
         * FinalizationBlockerCategory
         * @description Why an assessment cannot be finalized yet (ADR-0058).
         *
         *     A closed enum rather than free-text messages: the frontend disables
         *     a button and renders a checklist from these, and parsing English
         *     prose to decide that would break the first time the wording is
         *     improved.
         * @enum {string}
         */
        FinalizationBlockerCategory: "pending_ai_review" | "unresolved_evidence_request" | "unsupported_satisfied_finding" | "unsupported_not_applicable_finding" | "framework_version_unresolved";
        /**
         * FinalizationReadiness
         * @description Whether an assessment may be finalized, and what stands in the way.
         *
         *     Gaps do NOT appear here. A finalized assessment that reports an
         *     organization as non-compliant is a legitimate, complete result — the
         *     point of the platform. What blocks finalization is unfinished
         *     *review work*: unreviewed AI proposals, outstanding evidence
         *     requests, and findings that move a score without the evidence to
         *     support it.
         */
        FinalizationReadiness: {
            /** Assessment Id */
            assessment_id: string;
            /** Status */
            status: string;
            /** Is Ready */
            is_ready: boolean;
            /**
             * Blockers
             * @default []
             */
            blockers: components["schemas"]["FinalizationBlocker"][];
        };
        /** FrameworkDefinition */
        FrameworkDefinition: {
            /** Name */
            name: string;
            /** Full Name */
            full_name: string;
            /** Version */
            version: string;
            /** Source Title */
            source_title: string;
            /** Source Publisher */
            source_publisher: string;
            /** Source Date */
            source_date: string;
            /** Source Url */
            source_url: string;
            /** Retrieved Date */
            retrieved_date: string;
            /** Total Practices In Source */
            total_practices_in_source: number;
            /**
             * Scoring Model
             * @enum {string}
             */
            scoring_model: "cumulative_mil" | "coverage";
            /**
             * Mil Levels
             * @default []
             */
            mil_levels: components["schemas"]["MilLevelDefinition"][];
            /** Scoring Note */
            scoring_note: string;
            /** Domains */
            domains: components["schemas"]["Domain"][];
        };
        /** GapItem */
        GapItem: {
            /** Practice Id */
            practice_id: string;
            /** Practice Text */
            practice_text: string;
            /** Mil */
            mil?: number | null;
            /**
             * Has Pending Ai Proposal
             * @default false
             */
            has_pending_ai_proposal: boolean;
            /** @default insufficient_evidence */
            status: components["schemas"]["PracticeFindingStatus"];
            /** Finding Rationale */
            finding_rationale?: string | null;
            /**
             * Cited Evidence
             * @default []
             */
            cited_evidence: components["schemas"]["EvidenceCitation"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionJobFailure
         * @description Why an ingestion job failed, as a closed set rather than prose.
         *
         *     Same discipline as ADR-0058's FinalizationBlockerCategory: the UI
         *     decides what to render and whether a retry is worth offering, and
         *     parsing English to make that decision breaks the first time the
         *     wording improves. The human-readable detail lives alongside this in
         *     failure_message; this field is what code branches on.
         * @enum {string}
         */
        IngestionJobFailure: "unsupported_document" | "unknown_superseded_document" | "too_large" | "interrupted" | "internal_error";
        /**
         * IngestionJobStatus
         * @enum {string}
         */
        IngestionJobStatus: "queued" | "running" | "succeeded" | "failed";
        /**
         * IngestionJobView
         * @description One ingestion job as the API returns it.
         *
         *     Deliberately not the IngestionJob table row: parse_warnings is a
         *     real list here rather than the JSON string the row stores, and
         *     callers should not be reading a persistence detail. The success
         *     fields mirror IngestionResult exactly, so a client that already
         *     handles the synchronous response can reuse the same rendering once
         *     status is "succeeded".
         */
        IngestionJobView: {
            /** Id */
            id: string;
            status: components["schemas"]["IngestionJobStatus"];
            /** Filename */
            filename: string;
            /** Submitter */
            submitter?: string | null;
            /** Supersedes Document Id */
            supersedes_document_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Document Id */
            document_id?: string | null;
            /** Chunk Count */
            chunk_count?: number | null;
            parse_status?: components["schemas"]["ParseStatus"] | null;
            /** Parser Version */
            parser_version?: string | null;
            /** Embedding Backend */
            embedding_backend?: string | null;
            /** Parse Warnings */
            parse_warnings?: string[];
            failure_category?: components["schemas"]["IngestionJobFailure"] | null;
            /** Failure Message */
            failure_message?: string | null;
        };
        /**
         * IngestionResult
         * @description Returned by the ingestion API and service layer.
         */
        IngestionResult: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            parse_status: components["schemas"]["ParseStatus"];
            /** Parse Warnings */
            parse_warnings?: string[];
            /** Chunk Count */
            chunk_count: number;
            /** Embedding Backend */
            embedding_backend: string;
            /** Parser Version */
            parser_version: string;
        };
        /** LinkEvidenceRequest */
        LinkEvidenceRequest: {
            /** Document Id */
            document_id: string;
            /** Practice Reference */
            practice_reference: string;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Note */
            note?: string | null;
            /** @default manual */
            source: components["schemas"]["EvidenceSource"];
        };
        /** MilLevelDefinition */
        MilLevelDefinition: {
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** Objective */
        Objective: {
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Practices */
            practices: components["schemas"]["Practice"][];
            /**
             * Purpose
             * @default
             */
            purpose: string;
        };
        /**
         * OverallSummary
         * @description Deliberately does NOT average domain scores across a
         *     cumulative_mil framework — MIL is an ordinal scale (see
         *     c2m2-expert skill), and averaging ordinal values into a single
         *     number would misrepresent it exactly the way R-15 in the risk
         *     register warns against. cumulative_mil frameworks get a
         *     count-based headline instead; coverage frameworks, whose per-domain
         *     scores are already true fractions, get a legitimate weighted
         *     average. See ADR-0012.
         */
        OverallSummary: {
            /** Scoring Model */
            scoring_model: string;
            /** Headline */
            headline: string;
            /** Populated Domains */
            populated_domains: number;
            /** Total Domains */
            total_domains: number;
            /** Domains At Mil1 Or Above */
            domains_at_mil1_or_above?: number | null;
            /** Overall Coverage Fraction */
            overall_coverage_fraction?: number | null;
        };
        /**
         * ParseStatus
         * @enum {string}
         */
        ParseStatus: "success" | "success_ocr" | "success_partial_ocr" | "unsupported_scanned" | "encoding_failure" | "empty" | "failed";
        /** Practice */
        Practice: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Mil */
            mil?: number | null;
            /**
             * Equivalents
             * @default []
             */
            equivalents: components["schemas"]["Equivalent"][];
            /**
             * Applicability
             * @default
             */
            applicability: string;
            /**
             * Canonical Concepts
             * @default []
             */
            canonical_concepts: string[];
        };
        /**
         * PracticeFinding
         * @description A human reviewer's explicit, current compliance judgment for one
         *     practice within one assessment (ADR-0030). At most one row per
         *     (assessment_id, practice_reference) — repositories/
         *     assessment_repository.py's set_practice_finding() upserts by that
         *     pair and writes a PracticeFindingChange row on every transition, the
         *     same append-only-history pattern AssessmentStatusChange already
         *     established for assessment-level status.
         *
         *     Optional and additive: an assessment with zero PracticeFinding rows
         *     scores and reports identically to how it did before this table
         *     existed — see services/scoring_service.py's excluded_practice_ids
         *     parameter and services/assessment_service.py.compute_scores.
         */
        PracticeFinding: {
            /** Id */
            id?: string;
            /** Assessment Id */
            assessment_id: string;
            /** Practice Reference */
            practice_reference: string;
            status: components["schemas"]["PracticeFindingStatus"];
            /** Rationale */
            rationale: string;
            /**
             * Set By
             * @default human
             */
            set_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * PracticeFindingChange
         * @description Append-only audit trail for PracticeFinding, mirroring
         *     AssessmentStatusChange. Every set_practice_finding() call writes one
         *     row here, including the very first (from_status=None) — so "what did
         *     we used to think about this practice, and when did that change" is
         *     always answerable, not just "what do we think now."
         */
        PracticeFindingChange: {
            /** Id */
            id?: string;
            /** Assessment Id */
            assessment_id: string;
            /** Practice Reference */
            practice_reference: string;
            from_status?: components["schemas"]["PracticeFindingStatus"] | null;
            to_status: components["schemas"]["PracticeFindingStatus"];
            /** Rationale */
            rationale: string;
            /**
             * Set By
             * @default human
             */
            set_by: string;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at?: string;
        };
        /**
         * PracticeFindingStatus
         * @description A human reviewer's explicit compliance judgment for one practice,
         *     distinct from EvidenceReviewStatus (which judges a single proposed
         *     evidence-to-practice LINK, not the practice's overall compliance
         *     state). Exists to close a real, confirmed scoring gap: without this,
         *     "no evidence has been linked yet" and "evidence was reviewed and
         *     shown the control is absent" both collapse to the same "not in
         *     performed_practice_ids" outcome in services/scoring_service.py — see
         *     ADR-0030.
         * @enum {string}
         */
        PracticeFindingStatus: "satisfied" | "partially_satisfied" | "not_satisfied" | "insufficient_evidence" | "not_applicable";
        /**
         * RedactionMatch
         * @description One specific redaction/pseudonymization applied during a
         *     sanitization pass — the "diff" a human reviewer approves or
         *     rejects, per the mission's "preview/diff, human approval" flow.
         */
        RedactionMatch: {
            category: components["schemas"]["SensitivityCategory"];
            /** Field Path */
            field_path: string;
            /** Original Text */
            original_text: string;
            /** Replacement */
            replacement: string;
        };
        /** RequestMoreEvidenceRequest */
        RequestMoreEvidenceRequest: {
            /** Note */
            note: string;
            /** Requested By */
            requested_by: string;
        };
        /**
         * ResolutionItem
         * @description One entry in the prioritized gap list. Prioritization is
         *     effort-based (fewest missing practices first within a tier), not a
         *     fabricated impact score — see ADR-0012 for why "quick wins" (small,
         *     concrete, closeable gaps) is the honest framing this project can
         *     support without inventing a business-impact number it cannot back.
         */
        ResolutionItem: {
            /** Domain Short Code */
            domain_short_code: string;
            /** Domain Full Name */
            domain_full_name: string;
            /** Missing Count */
            missing_count: number;
            /** Rationale */
            rationale: string;
        };
        /** ResolveEvidenceRequestRequest */
        ResolveEvidenceRequestRequest: {
            /** Resolved By */
            resolved_by: string;
        };
        /** ReviewEvidenceRequest */
        ReviewEvidenceRequest: {
            decision: components["schemas"]["EvidenceReviewStatus"];
            /** Corrected Practice Reference */
            corrected_practice_reference?: string | null;
            /** Note */
            note?: string | null;
        };
        /**
         * SanitizationApproval
         * @description A human's explicit sign-off on one specific sanitized report
         *     (ADR-0032) — "internal assessment -> sanitization -> preview/diff ->
         *     human approval -> sanitized export", never a silent step.
         *
         *     sanitized_content_hash pins exactly what was approved: a SHA-256 of
         *     the sanitized DashboardReport's own JSON content, recomputed fresh
         *     every time a sanitized export is requested
         *     (services/assessment_service.py.generate_dashboard_pdf/xlsx). If
         *     anything the report is built from has changed since approval (a new
         *     finding, an edited rationale, a newly accepted evidence link), the
         *     freshly recomputed hash will not match this stored one, and export
         *     is blocked (SanitizationApprovalStaleError) until re-approved —
         *     approval is tied to specific content, not to "sanitization is on"
         *     as a standing toggle that could authorize a materially different
         *     report than what was actually reviewed.
         */
        SanitizationApproval: {
            /** Id */
            id?: string;
            /** Assessment Id */
            assessment_id: string;
            /** Sanitized Content Hash */
            sanitized_content_hash: string;
            /** Custom Terms Json */
            custom_terms_json: string;
            /** Approved By */
            approved_by: string;
            /**
             * Approved At
             * Format: date-time
             */
            approved_at?: string;
        };
        /**
         * SanitizationPreview
         * @description Never persisted by itself — a preview is regenerated fresh on
         *     every request (services/sanitization_service.py never trusts a
         *     caller-supplied "already redacted" report). Only
         *     SanitizationApproval (models/assessment.py), which stores a hash of
         *     a specific sanitized_report content, is persisted — and only after
         *     an explicit approval call.
         */
        SanitizationPreview: {
            /** Matches */
            matches: components["schemas"]["RedactionMatch"][];
            sanitized_report: components["schemas"]["DashboardReport"];
        };
        /** SanitizationPreviewRequest */
        SanitizationPreviewRequest: {
            /**
             * Custom Terms
             * @default []
             */
            custom_terms: string[];
        };
        /**
         * SealVerification
         * @description Whether a finalized assessment still matches the seal written at
         *     finalization (R-12). Both digests are returned so a holder of an
         *     exported report can compare against what the export printed.
         */
        SealVerification: {
            /** Assessment Id */
            assessment_id: string;
            status: components["schemas"]["SealVerificationStatus"];
            /** Sealed Digest */
            sealed_digest?: string | null;
            /** Computed Digest */
            computed_digest?: string | null;
            /** Sealed At */
            sealed_at?: string | null;
            /** Seal Version */
            seal_version?: string | null;
            /** Detail */
            detail: string;
        };
        /**
         * SealVerificationStatus
         * @description The outcome of checking a finalized assessment against its seal.
         *
         *     Four values, not a boolean: "no seal exists" and "the seal does not
         *     match" are opposite situations that a boolean would collapse into
         *     the same false. An unsealed assessment is unverified, which is not
         *     the same as untrustworthy; an altered one is a finding.
         * @enum {string}
         */
        SealVerificationStatus: "verified" | "altered" | "unsealed" | "unverifiable";
        /**
         * SensitivityCategory
         * @description The mission-named categories this project can actually detect.
         *     Names, facility/location names, and employee/account/vendor/customer
         *     identifiers are NOT pattern-detectable without either a maintained
         *     gazetteer this project doesn't have or a local NER model this
         *     project has not evaluated (a decision of comparable weight to
         *     ADR-0006/0008's embedding-backend choices, not made unilaterally
         *     here) — those are handled via CUSTOM_TERM instead: an explicit,
         *     reviewer-supplied list, never guessed. See ADR-0032.
         * @enum {string}
         */
        SensitivityCategory: "email" | "phone" | "ip_address" | "hostname_or_url" | "custom_term";
        /** SetPracticeFindingRequest */
        SetPracticeFindingRequest: {
            status: components["schemas"]["PracticeFindingStatus"];
            /** Rationale */
            rationale: string;
        };
        /** Situation */
        Situation: {
            /** Assessment Id */
            assessment_id: string;
            /** Assessment Name */
            assessment_name: string;
            /** Framework Name */
            framework_name: string;
            /** Scoring Model */
            scoring_model: string;
            /** Status */
            status: string;
            /** Total Evidence Links */
            total_evidence_links: number;
            /** Accepted Count */
            accepted_count: number;
            /** Edited Count */
            edited_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Pending Ai Review Count */
            pending_ai_review_count: number;
            /** Unpopulated Domains */
            unpopulated_domains: string[];
            /**
             * Unsupported Satisfied Practices
             * @default []
             */
            unsupported_satisfied_practices: string[];
            /**
             * Unsupported Not Applicable Practices
             * @default []
             */
            unsupported_not_applicable_practices: string[];
            /** Finalization Seal */
            finalization_seal?: string | null;
            /**
             * So What
             * @default []
             */
            so_what: string[];
        };
        /** StatusTransitionRequest */
        StatusTransitionRequest: {
            status: components["schemas"]["AssessmentStatus"];
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_document_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_document_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_document_async_ingest_async_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_document_async_ingest_async_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestion_jobs_ingest_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_job_ingest_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessments_assessments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"][];
                };
            };
        };
    };
    create_assessment_assessments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssessmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_status_assessments__assessment_id__status_post: {
        parameters: {
            query?: never;
            header?: {
                "x-remote-user"?: string | null;
            };
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_finalization_readiness_assessments__assessment_id__finalization_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizationReadiness"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_seal_assessments__assessment_id__verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SealVerification"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_history_assessments__assessment_id__status_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentStatusChange"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_assessments__assessment_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLink"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_evidence_assessments__assessment_id__evidence_post: {
        parameters: {
            query?: never;
            header?: {
                "x-remote-user"?: string | null;
            };
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scores_assessments__assessment_id__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_assessments__assessment_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_pdf_assessments__assessment_id__report_pdf_get: {
        parameters: {
            query?: {
                sanitized?: boolean;
            };
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_xlsx_assessments__assessment_id__report_xlsx_get: {
        parameters: {
            query?: {
                sanitized?: boolean;
            };
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_sanitization_assessments__assessment_id__sanitization_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SanitizationPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SanitizationPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_sanitization_assessments__assessment_id__sanitization_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveSanitizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SanitizationApproval"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_evidence_assessments__assessment_id__evidence__evidence_link_id__review_post: {
        parameters: {
            query?: never;
            header?: {
                "x-remote-user"?: string | null;
            };
            path: {
                assessment_id: string;
                evidence_link_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_practice_finding_assessments__assessment_id__practice_findings__practice_reference__put: {
        parameters: {
            query?: never;
            header?: {
                "x-remote-user"?: string | null;
            };
            path: {
                assessment_id: string;
                practice_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPracticeFindingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeFinding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_practice_findings_assessments__assessment_id__practice_findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeFinding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_finding_history_assessments__assessment_id__practice_findings__practice_reference__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
                practice_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeFindingChange"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_more_evidence_assessments__assessment_id__practice_findings__practice_reference__evidence_requests_post: {
        parameters: {
            query?: never;
            header?: {
                "x-remote-user"?: string | null;
            };
            path: {
                assessment_id: string;
                practice_reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestMoreEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_requests_assessments__assessment_id__evidence_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRequest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_evidence_request_assessments__assessment_id__evidence_requests__request_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-remote-user"?: string | null;
            };
            path: {
                assessment_id: string;
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveEvidenceRequestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_mappings_assessments__assessment_id__propose_mappings_post: {
        parameters: {
            query?: never;
            header?: {
                "x-remote-user"?: string | null;
            };
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLink"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_with_assessment_assessments__assessment_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_framework_frameworks__name__get: {
        parameters: {
            query?: {
                version?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_framework_versions_frameworks__name__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
