import type { components } from './schema'

export type Assessment = components['schemas']['Assessment']
export type AssessmentStatus = components['schemas']['AssessmentStatus']
export type AssessmentStatusChange = components['schemas']['AssessmentStatusChange']
export type ChatResponse = components['schemas']['ChatResponse']
export type ChatResult = components['schemas']['ChatResult']
export type CreateAssessmentRequest = components['schemas']['CreateAssessmentRequest']
export type DashboardReport = components['schemas']['DashboardReport']
export type Domain = components['schemas']['Domain']
export type DomainGapGroup = components['schemas']['DomainGapGroup']
export type EvidenceLink = components['schemas']['EvidenceLink']
export type EvidenceReviewStatus = components['schemas']['EvidenceReviewStatus']
export type EvidenceSource = components['schemas']['EvidenceSource']
export type FrameworkDefinition = components['schemas']['FrameworkDefinition']
export type GapItem = components['schemas']['GapItem']
export type IngestionResult = components['schemas']['IngestionResult']
export type LinkEvidenceRequest = components['schemas']['LinkEvidenceRequest']
export type Objective = components['schemas']['Objective']
export type OverallSummary = components['schemas']['OverallSummary']
export type ParseStatus = components['schemas']['ParseStatus']
export type Practice = components['schemas']['Practice']
export type ResolutionItem = components['schemas']['ResolutionItem']
export type ReviewEvidenceRequest = components['schemas']['ReviewEvidenceRequest']
export type Situation = components['schemas']['Situation']
export type StatusTransitionRequest = components['schemas']['StatusTransitionRequest']
