"""Unit tests for PDF/XLSX rendering (Sprint 7). Builds DashboardReport
instances directly (not via build_dashboard) since export_service is a
pure rendering step over an already-built report — see
services/export_service.py and ADR-0013. Verifies output by reading the
generated bytes back with the same libraries a real consumer would use
(pypdf, already a project dependency; openpyxl), not just checking a
byte count.
"""

from __future__ import annotations

import io

import openpyxl
from pypdf import PdfReader

from compliance_platform.models.assessment import EvidenceReviewStatus, PracticeFindingStatus
from compliance_platform.models.report import (
    DashboardReport,
    DomainGapGroup,
    DomainProgress,
    EvidenceCitation,
    GapItem,
    OverallSummary,
    ResolutionItem,
    Situation,
)
from compliance_platform.services.export_service import build_pdf_report, build_xlsx_report


def _dashboard(
    *,
    assessment_name: str = "Q3 C2M2 Self Assessment",
    domain_full_name: str = "Identity and Access Management",
) -> DashboardReport:
    situation = Situation(
        assessment_id="a1",
        assessment_name=assessment_name,
        framework_name="C2M2",
        scoring_model="cumulative_mil",
        status="in_review",
        total_evidence_links=5,
        accepted_count=3,
        edited_count=1,
        rejected_count=1,
        pending_ai_review_count=2,
        unpopulated_domains=["RISK"],
    )
    gaps = [
        GapItem(
            practice_id="ACCESS-1d",
            practice_text="Password strength and reuse restrictions are defined and enforced",
            mil=2,
            has_pending_ai_proposal=True,
        ),
        GapItem(
            practice_id="ACCESS-1e",
            practice_text="Identity repositories are reviewed and updated periodically",
            mil=2,
            has_pending_ai_proposal=False,
        ),
    ]
    complication = [
        DomainGapGroup(
            domain_short_code="ACCESS",
            domain_full_name=domain_full_name,
            total_practices=35,
            met_practices=9,
            gaps=gaps,
            so_what=f"{domain_full_name} is at MIL1: 26 of 35 practices still need evidence.",
        )
    ]
    resolution = [
        ResolutionItem(
            domain_short_code="ACCESS",
            domain_full_name=domain_full_name,
            missing_count=26,
            rationale=(
                "Already 9 of 35 practices met; only 26 remaining to fully close this domain."
            ),
        )
    ]
    overall = OverallSummary(
        scoring_model="cumulative_mil",
        headline="1 of 2 assessable domains have reached MIL1 or higher.",
        populated_domains=2,
        total_domains=10,
        domains_at_mil1_or_above=1,
    )
    return DashboardReport(
        situation=situation,
        domain_scores={"ACCESS": 1.0, "ASSET": 0.0},
        overall=overall,
        complication=complication,
        resolution=resolution,
    )


def test_pdf_report_starts_with_pdf_magic_bytes() -> None:
    pdf_bytes = build_pdf_report(_dashboard())
    assert pdf_bytes.startswith(b"%PDF")


def test_pdf_report_contains_key_facts_extractable_by_pypdf() -> None:
    pdf_bytes = build_pdf_report(_dashboard())
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)

    assert "Q3 C2M2 Self Assessment" in text
    assert "ACCESS-1d" in text
    assert "AI-proposed, pending review" in text
    assert "1 of 2 assessable domains" in text
    assert "RISK" in text  # unpopulated domain still named, not silently dropped


def test_pdf_report_survives_em_dash_in_source_text_without_crashing() -> None:
    dashboard = _dashboard(domain_full_name="Cross—Domain Access Controls")
    pdf_bytes = build_pdf_report(dashboard)
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)
    assert "Cross - Domain Access Controls" in text  # em dash translated, not dropped/crashed


def test_xlsx_report_has_expected_sheets() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    assert wb.sheetnames == [
        "Situation",
        "Domain Scores",
        "Domain Completion",
        "Gaps",
        "Resolution",
    ]


def test_xlsx_situation_sheet_carries_review_status_counts() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    ws = wb["Situation"]
    rows = {row[0].value: row[1].value for row in ws.iter_rows(min_row=2)}
    assert rows["Assessment Name"] == "Q3 C2M2 Self Assessment"
    assert rows["Accepted"] == 3
    assert rows["Pending AI Review (not yet scored)"] == 2
    assert rows["Unpopulated Domains"] == "RISK"


def test_xlsx_gaps_sheet_flattens_domain_groups_with_ai_flag() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    ws = wb["Gaps"]
    data_rows = list(ws.iter_rows(min_row=2, values_only=True))
    assert len(data_rows) == 2
    practice_ids = {row[2] for row in data_rows}
    assert practice_ids == {"ACCESS-1d", "ACCESS-1e"}
    ai_flagged = {row[2]: row[5] for row in data_rows}
    assert ai_flagged["ACCESS-1d"] == "Yes"
    assert ai_flagged["ACCESS-1e"] == "No"


def test_xlsx_resolution_sheet_ranks_items_in_order() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    ws = wb["Resolution"]
    data_rows = list(ws.iter_rows(min_row=2, values_only=True))
    assert data_rows[0][0] == 1  # rank
    assert data_rows[0][1] == "ACCESS"
    assert data_rows[0][3] == 26


# --- Evidence citation on gaps (Sprint 18, ADR-0040) ---


def _dashboard_with_finding_and_citation() -> DashboardReport:
    dashboard = _dashboard()
    gap = dashboard.complication[0].gaps[0]
    updated_gap = gap.model_copy(
        update={
            "status": PracticeFindingStatus.NOT_SATISFIED,
            "finding_rationale": "Shared service account credentials found in plaintext.",
            "cited_evidence": [
                EvidenceCitation(
                    evidence_link_id="link-1",
                    document_id="doc-incident-report",
                    review_status=EvidenceReviewStatus.ACCEPTED,
                )
            ],
        }
    )
    dashboard.complication[0].gaps[0] = updated_gap
    return dashboard


def test_pdf_report_renders_gap_status_rationale_and_evidence_citation() -> None:
    pdf_bytes = build_pdf_report(_dashboard_with_finding_and_citation())
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)

    assert "not satisfied" in text
    assert "Shared service account credentials found in plaintext" in text
    assert "doc-incident-report" in text
    assert "accepted" in text


def test_pdf_report_omits_status_line_for_a_gap_with_no_finding_at_all() -> None:
    # The genuinely-no-evidence-reviewed-yet case (INSUFFICIENT_EVIDENCE,
    # no rationale) shouldn't clutter every gap line with a redundant
    # "Status: insufficient evidence" -- only a real finding or a
    # non-empty rationale earns the extra line. ("Status:" alone isn't
    # a safe check -- the report header already has an unrelated
    # "Status: in_review" line for the assessment itself.)
    pdf_bytes = build_pdf_report(_dashboard())  # default gaps: no status/rationale set
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)
    assert "insufficient evidence" not in text
    assert "Evidence:" not in text


def test_xlsx_gaps_sheet_carries_status_rationale_and_cited_evidence() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard_with_finding_and_citation())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    ws = wb["Gaps"]
    data_rows = list(ws.iter_rows(min_row=2, values_only=True))
    first_row = next(row for row in data_rows if row[2] == "ACCESS-1d")
    assert first_row[6] == "not satisfied"
    assert "plaintext" in first_row[7]
    assert "doc-incident-report" in first_row[8]
    assert "accepted" in first_row[8]


# --- Document-supersession flagging (Sprint 18, ADR-0050) ---


def _dashboard_with_superseded_citation() -> DashboardReport:
    dashboard = _dashboard()
    gap = dashboard.complication[0].gaps[0]
    updated_gap = gap.model_copy(
        update={
            "cited_evidence": [
                EvidenceCitation(
                    evidence_link_id="link-1",
                    document_id="doc-old-policy",
                    review_status=EvidenceReviewStatus.ACCEPTED,
                    is_superseded=True,
                )
            ],
        }
    )
    dashboard.complication[0].gaps[0] = updated_gap
    return dashboard


def test_pdf_report_flags_superseded_cited_evidence() -> None:
    pdf_bytes = build_pdf_report(_dashboard_with_superseded_citation())
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)
    assert "doc-old-policy" in text
    assert "SUPERSEDED" in text


def test_pdf_report_does_not_flag_a_non_superseded_citation() -> None:
    pdf_bytes = build_pdf_report(_dashboard_with_finding_and_citation())
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)
    assert "SUPERSEDED" not in text


def test_xlsx_gaps_sheet_flags_superseded_cited_evidence() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard_with_superseded_citation())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    ws = wb["Gaps"]
    data_rows = list(ws.iter_rows(min_row=2, values_only=True))
    first_row = next(row for row in data_rows if row[2] == "ACCESS-1d")
    assert "doc-old-policy" in first_row[8]
    assert "SUPERSEDED" in first_row[8]


# ---- Domain completion and the MIL gate in both exports (ADR-0069) ----
#
# ADR-0066 and ADR-0068 shipped two dashboard visuals and disclosed, twice,
# that the exports carried neither them nor the MIL-gate sentence. A
# reviewer who read that explanation on screen and then sent the PDF had
# sent something without it. These cover closing that.


def _progress_dashboard(scoring_model: str = "cumulative_mil") -> DashboardReport:
    dashboard = _dashboard()
    dashboard.overall = OverallSummary(
        scoring_model=scoring_model,
        headline="headline",
        populated_domains=2,
        total_domains=10,
        domains_at_mil1_or_above=1,
    )
    dashboard.domain_progress = [
        DomainProgress(
            short_code="ACCESS",
            full_name="Identity and Access Management",
            met_practices=9,
            total_practices=10,
            score=0.0,
            blocking_mil=1,
            blocking_practice_count=1,
            gate_note=(
                "1 practice(s) at MIL1 still unmet, so this domain cannot score above MIL0 "
                "however complete it looks."
            ),
        ),
        DomainProgress(
            short_code="ASSET",
            full_name="Asset, Change, and Configuration Management",
            met_practices=36,
            total_practices=36,
            score=3.0,
        ),
    ]
    return dashboard


def _pdf_text(dashboard: DashboardReport) -> str:
    """Extracted text with whitespace collapsed.

    The renderer wraps paragraphs to the page width, so a sentence this
    file asserts on is split across lines in the output. Collapsing
    whitespace keeps the assertions about what the document SAYS rather
    than about where fpdf happened to break the line.
    """
    reader = PdfReader(io.BytesIO(build_pdf_report(dashboard)))
    raw = "\n".join(page.extract_text() for page in reader.pages)
    return " ".join(raw.split())


def test_pdf_carries_domain_completion_including_a_fully_met_domain() -> None:
    """Complication lists only domains with gaps, so a PDF reader could
    not previously tell a finished domain from one nobody had started."""
    text = _pdf_text(_progress_dashboard())

    assert "Domain Completion" in text
    assert "9/10 practices" in text
    assert "36/36 practices" in text
    assert "Asset, Change, and Configuration Management" in text


def test_pdf_carries_the_mil_gate_sentence() -> None:
    """The information that existed only on screen. Without it a 90% bar
    beside MIL0 reads as a defect in the report."""
    text = _pdf_text(_progress_dashboard())

    assert "1 practice(s) at MIL1 still unmet" in text
    assert "cannot score above MIL0" in text


def test_pdf_states_that_bars_are_not_the_maturity_score() -> None:
    text = _pdf_text(_progress_dashboard())
    assert "not the maturity score" in text


def test_pdf_says_the_opposite_for_a_coverage_framework() -> None:
    """Under coverage the bar and the score ARE the same measure, so the
    caveat would be wrong rather than merely unnecessary."""
    text = _pdf_text(_progress_dashboard(scoring_model="coverage"))

    assert "same measure as this framework's coverage score" in text
    assert "not the maturity score" not in text


def test_pdf_labels_a_domain_score_in_its_own_units() -> None:
    """Never a bare float: the same number means MIL under one scoring
    model and a fraction under the other (R-15)."""
    assert "MIL0" in _pdf_text(_progress_dashboard())
    assert "0% coverage" in _pdf_text(_progress_dashboard(scoring_model="coverage"))


def test_pdf_still_renders_with_no_domain_progress() -> None:
    """An older report, or one whose domains are all untranscribed. The
    section is skipped rather than printed empty."""
    dashboard = _dashboard()
    assert dashboard.domain_progress == []

    text = _pdf_text(dashboard)

    assert "Domain Completion" not in text
    assert "Complication" in text


def _sheet_rows(dashboard: DashboardReport, sheet: str) -> list[tuple]:
    wb = openpyxl.load_workbook(io.BytesIO(build_xlsx_report(dashboard)))
    return list(wb[sheet].values)


def test_xlsx_completion_sheet_carries_the_numbers_behind_the_bars() -> None:
    rows = _sheet_rows(_progress_dashboard(), "Domain Completion")

    header, access, asset = rows
    assert header[:5] == (
        "Domain Code",
        "Domain Name",
        "Practices Met",
        "Applicable Practices",
        "Completion",
    )
    assert access[0] == "ACCESS"
    assert access[2] == 9
    assert access[3] == 10
    # A real fraction rather than a formatted string, so the column sorts
    # and charts as a number in the reader's own spreadsheet.
    assert access[4] == 0.9
    assert asset[4] == 1.0


def test_xlsx_completion_sheet_carries_the_gate_and_its_sentence() -> None:
    rows = _sheet_rows(_progress_dashboard(), "Domain Completion")
    _, access, asset = rows

    assert access[6] == 1
    assert access[7] == 1
    assert "cannot score above MIL0" in access[8]
    # Nothing blocking the fully-met domain, and no sentence invented for
    # it. openpyxl reads a blank cell back as None, which is what an
    # empty string written into a spreadsheet becomes.
    assert asset[6] is None
    assert asset[8] is None


def test_xlsx_domain_scores_header_names_the_unit() -> None:
    """This column was a bare "Score" whose meaning depends on the
    framework — the R-15 ambiguity, sitting in a spreadsheet where a
    reader would sort by it."""
    mil_header = _sheet_rows(_progress_dashboard(), "Domain Scores")[0]
    coverage_header = _sheet_rows(_progress_dashboard(scoring_model="coverage"), "Domain Scores")[0]

    assert mil_header == ("Domain", "Score (MIL 0-3, ordinal)")
    assert coverage_header == ("Domain", "Score (coverage, 0.0-1.0)")


def test_xlsx_completion_sheet_is_empty_but_present_without_progress() -> None:
    rows = _sheet_rows(_dashboard(), "Domain Completion")
    assert len(rows) == 1  # header only
