"""Unit tests for PDF/XLSX rendering (Sprint 7). Builds DashboardReport
instances directly (not via build_dashboard) since export_service is a
pure rendering step over an already-built report — see
services/export_service.py and ADR-0013. Verifies output by reading the
generated bytes back with the same libraries a real consumer would use
(pypdf, already a project dependency; openpyxl), not just checking a
byte count.
"""

from __future__ import annotations

import io

import openpyxl
from pypdf import PdfReader

from compliance_platform.models.assessment import EvidenceReviewStatus, PracticeFindingStatus
from compliance_platform.models.report import (
    DashboardReport,
    DomainGapGroup,
    EvidenceCitation,
    GapItem,
    OverallSummary,
    ResolutionItem,
    Situation,
)
from compliance_platform.services.export_service import build_pdf_report, build_xlsx_report


def _dashboard(
    *,
    assessment_name: str = "Q3 C2M2 Self Assessment",
    domain_full_name: str = "Identity and Access Management",
) -> DashboardReport:
    situation = Situation(
        assessment_id="a1",
        assessment_name=assessment_name,
        framework_name="C2M2",
        scoring_model="cumulative_mil",
        status="in_review",
        total_evidence_links=5,
        accepted_count=3,
        edited_count=1,
        rejected_count=1,
        pending_ai_review_count=2,
        unpopulated_domains=["RISK"],
    )
    gaps = [
        GapItem(
            practice_id="ACCESS-1d",
            practice_text="Password strength and reuse restrictions are defined and enforced",
            mil=2,
            has_pending_ai_proposal=True,
        ),
        GapItem(
            practice_id="ACCESS-1e",
            practice_text="Identity repositories are reviewed and updated periodically",
            mil=2,
            has_pending_ai_proposal=False,
        ),
    ]
    complication = [
        DomainGapGroup(
            domain_short_code="ACCESS",
            domain_full_name=domain_full_name,
            total_practices=35,
            met_practices=9,
            gaps=gaps,
            so_what=f"{domain_full_name} is at MIL1: 26 of 35 practices still need evidence.",
        )
    ]
    resolution = [
        ResolutionItem(
            domain_short_code="ACCESS",
            domain_full_name=domain_full_name,
            missing_count=26,
            rationale=(
                "Already 9 of 35 practices met; only 26 remaining to fully close this domain."
            ),
        )
    ]
    overall = OverallSummary(
        scoring_model="cumulative_mil",
        headline="1 of 2 assessable domains have reached MIL1 or higher.",
        populated_domains=2,
        total_domains=10,
        domains_at_mil1_or_above=1,
    )
    return DashboardReport(
        situation=situation,
        domain_scores={"ACCESS": 1.0, "ASSET": 0.0},
        overall=overall,
        complication=complication,
        resolution=resolution,
    )


def test_pdf_report_starts_with_pdf_magic_bytes() -> None:
    pdf_bytes = build_pdf_report(_dashboard())
    assert pdf_bytes.startswith(b"%PDF")


def test_pdf_report_contains_key_facts_extractable_by_pypdf() -> None:
    pdf_bytes = build_pdf_report(_dashboard())
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)

    assert "Q3 C2M2 Self Assessment" in text
    assert "ACCESS-1d" in text
    assert "AI-proposed, pending review" in text
    assert "1 of 2 assessable domains" in text
    assert "RISK" in text  # unpopulated domain still named, not silently dropped


def test_pdf_report_survives_em_dash_in_source_text_without_crashing() -> None:
    dashboard = _dashboard(domain_full_name="Cross—Domain Access Controls")
    pdf_bytes = build_pdf_report(dashboard)
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)
    assert "Cross - Domain Access Controls" in text  # em dash translated, not dropped/crashed


def test_xlsx_report_has_expected_sheets() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    assert wb.sheetnames == ["Situation", "Domain Scores", "Gaps", "Resolution"]


def test_xlsx_situation_sheet_carries_review_status_counts() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    ws = wb["Situation"]
    rows = {row[0].value: row[1].value for row in ws.iter_rows(min_row=2)}
    assert rows["Assessment Name"] == "Q3 C2M2 Self Assessment"
    assert rows["Accepted"] == 3
    assert rows["Pending AI Review (not yet scored)"] == 2
    assert rows["Unpopulated Domains"] == "RISK"


def test_xlsx_gaps_sheet_flattens_domain_groups_with_ai_flag() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    ws = wb["Gaps"]
    data_rows = list(ws.iter_rows(min_row=2, values_only=True))
    assert len(data_rows) == 2
    practice_ids = {row[2] for row in data_rows}
    assert practice_ids == {"ACCESS-1d", "ACCESS-1e"}
    ai_flagged = {row[2]: row[5] for row in data_rows}
    assert ai_flagged["ACCESS-1d"] == "Yes"
    assert ai_flagged["ACCESS-1e"] == "No"


def test_xlsx_resolution_sheet_ranks_items_in_order() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    ws = wb["Resolution"]
    data_rows = list(ws.iter_rows(min_row=2, values_only=True))
    assert data_rows[0][0] == 1  # rank
    assert data_rows[0][1] == "ACCESS"
    assert data_rows[0][3] == 26


# --- Evidence citation on gaps (Sprint 18, ADR-0040) ---


def _dashboard_with_finding_and_citation() -> DashboardReport:
    dashboard = _dashboard()
    gap = dashboard.complication[0].gaps[0]
    updated_gap = gap.model_copy(
        update={
            "status": PracticeFindingStatus.NOT_SATISFIED,
            "finding_rationale": "Shared service account credentials found in plaintext.",
            "cited_evidence": [
                EvidenceCitation(
                    evidence_link_id="link-1",
                    document_id="doc-incident-report",
                    review_status=EvidenceReviewStatus.ACCEPTED,
                )
            ],
        }
    )
    dashboard.complication[0].gaps[0] = updated_gap
    return dashboard


def test_pdf_report_renders_gap_status_rationale_and_evidence_citation() -> None:
    pdf_bytes = build_pdf_report(_dashboard_with_finding_and_citation())
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)

    assert "not satisfied" in text
    assert "Shared service account credentials found in plaintext" in text
    assert "doc-incident-report" in text
    assert "accepted" in text


def test_pdf_report_omits_status_line_for_a_gap_with_no_finding_at_all() -> None:
    # The genuinely-no-evidence-reviewed-yet case (INSUFFICIENT_EVIDENCE,
    # no rationale) shouldn't clutter every gap line with a redundant
    # "Status: insufficient evidence" -- only a real finding or a
    # non-empty rationale earns the extra line. ("Status:" alone isn't
    # a safe check -- the report header already has an unrelated
    # "Status: in_review" line for the assessment itself.)
    pdf_bytes = build_pdf_report(_dashboard())  # default gaps: no status/rationale set
    reader = PdfReader(io.BytesIO(pdf_bytes))
    text = "\n".join(page.extract_text() for page in reader.pages)
    assert "insufficient evidence" not in text
    assert "Evidence:" not in text


def test_xlsx_gaps_sheet_carries_status_rationale_and_cited_evidence() -> None:
    xlsx_bytes = build_xlsx_report(_dashboard_with_finding_and_citation())
    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes))
    ws = wb["Gaps"]
    data_rows = list(ws.iter_rows(min_row=2, values_only=True))
    first_row = next(row for row in data_rows if row[2] == "ACCESS-1d")
    assert first_row[6] == "not satisfied"
    assert "plaintext" in first_row[7]
    assert "doc-incident-report" in first_row[8]
    assert "accepted" in first_row[8]
